function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID0\" class=\"headerLeftMenuInActive\"><a id=\"aID0\" href=\"#\" OnMouseOver=\"link('','index',this)\" class=\"leftMenuLinkHeadInActive\">Default mainpage</a></div>\n");
document.write("<div class=\"paragraphLeftMenu\">Directories</div>\n");
document.write("<div id=\"divID5456\" class=\"leftMenuInActive\"><a id=\"aID5456\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/at91lib/at91lib0',this)\" class=\"leftMenuLinkInActive\">at91lib</a></div>\n");
document.write("<div id=\"divID5502\" class=\"leftMenuInActive\"><a id=\"aID5502\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-adc-project/basicmi_adcmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-adc-project</a></div>\n");
document.write("<div id=\"divID5503\" class=\"leftMenuInActive\"><a id=\"aID5503\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-dataflash-project/basicmi_dataflashmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-dataflash-project</a></div>\n");
document.write("<div id=\"divID5504\" class=\"leftMenuInActive\"><a id=\"aID5504\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-dhrystone-project/basicmi_dhrystonemi_project0',this)\" class=\"leftMenuLinkInActive\">basic-dhrystone-project</a></div>\n");
document.write("<div id=\"divID5505\" class=\"leftMenuInActive\"><a id=\"aID5505\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-internalflash-project/basicmi_internalflashmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-internalflash-project</a></div>\n");
document.write("<div id=\"divID5506\" class=\"leftMenuInActive\"><a id=\"aID5506\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-iso7816-project/basicmi_iso7816mi_project0',this)\" class=\"leftMenuLinkInActive\">basic-iso7816-project</a></div>\n");
document.write("<div id=\"divID5507\" class=\"leftMenuInActive\"><a id=\"aID5507\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-pwm-project/basicmi_pwmmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-pwm-project</a></div>\n");
document.write("<div id=\"divID5508\" class=\"leftMenuInActive\"><a id=\"aID5508\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-rtt-project/basicmi_rttmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-rtt-project</a></div>\n");
document.write("<div id=\"divID5509\" class=\"leftMenuInActive\"><a id=\"aID5509\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-sd-spi-project/basicmi_sdmi_spimi_project0',this)\" class=\"leftMenuLinkInActive\">basic-sd-spi-project</a></div>\n");
document.write("<div id=\"divID5510\" class=\"leftMenuInActive\"><a id=\"aID5510\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-serialflash-project/basicmi_serialflashmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-serialflash-project</a></div>\n");
document.write("<div id=\"divID5511\" class=\"leftMenuInActive\"><a id=\"aID5511\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-twi-eeprom-project/basicmi_twimi_eeprommi_project0',this)\" class=\"leftMenuLinkInActive\">basic-twi-eeprom-project</a></div>\n");
document.write("<div id=\"divID5512\" class=\"leftMenuInActive\"><a id=\"aID5512\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/basic-usart-hw-handshaking-project/basicmi_usartmi_hwmi_handshakingmi_project0',this)\" class=\"leftMenuLinkInActive\">basic-usart-hw-handshaking-project</a></div>\n");
document.write("<div id=\"divID5513\" class=\"leftMenuInActive\"><a id=\"aID5513\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/getting-started-project/gettingmi_startedmi_project0',this)\" class=\"leftMenuLinkInActive\">getting-started-project</a></div>\n");
document.write("<div id=\"divID5514\" class=\"leftMenuInActive\"><a id=\"aID5514\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-ccid-project/usbmi_devicemi_ccidmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-ccid-project</a></div>\n");
document.write("<div id=\"divID5515\" class=\"leftMenuInActive\"><a id=\"aID5515\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-cdc-serial-project/usbmi_devicemi_cdcmi_serialmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-cdc-serial-project</a></div>\n");
document.write("<div id=\"divID5516\" class=\"leftMenuInActive\"><a id=\"aID5516\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-composite-cdchid-project/usbmi_devicemi_compositemi_cdchidmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-composite-cdchid-project</a></div>\n");
document.write("<div id=\"divID5517\" class=\"leftMenuInActive\"><a id=\"aID5517\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-composite-cdcmsd-project/usbmi_devicemi_compositemi_cdcmsdmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-composite-cdcmsd-project</a></div>\n");
document.write("<div id=\"divID5518\" class=\"leftMenuInActive\"><a id=\"aID5518\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-composite-hidmsd-project/usbmi_devicemi_compositemi_hidmsdmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-composite-hidmsd-project</a></div>\n");
document.write("<div id=\"divID5519\" class=\"leftMenuInActive\"><a id=\"aID5519\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-core-project/usbmi_devicemi_coremi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-core-project</a></div>\n");
document.write("<div id=\"divID5520\" class=\"leftMenuInActive\"><a id=\"aID5520\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-hid-keyboard-project/usbmi_devicemi_hidmi_keyboardmi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-hid-keyboard-project</a></div>\n");
document.write("<div id=\"divID5521\" class=\"leftMenuInActive\"><a id=\"aID5521\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-hid-mouse-project/usbmi_devicemi_hidmi_mousemi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-hid-mouse-project</a></div>\n");
document.write("<div id=\"divID5523\" class=\"leftMenuInActive\"><a id=\"aID5523\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-hid-transfer-project/usbmi_devicemi_hidmi_transfermi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-hid-transfer-project</a></div>\n");
document.write("<div id=\"divID5524\" class=\"leftMenuInActive\"><a id=\"aID5524\" href=\"#\" OnMouseOver=\"link('_dir','softpack-1.5/usb-device-massstorage-project/usbmi_devicemi_massstoragemi_project0',this)\" class=\"leftMenuLinkInActive\">usb-device-massstorage-project</a></div>\n");
if(divID != "" && aID != "")
{
document.getElementById(divID).className = divClassName;
document.getElementById(aID).className = aClassName;
}
}
