adc.h File Reference
Routines to use AT91 onboard ADC in polling mode.
#include `config.h`
Typedefs
typedef uint16_t adc_sample_t
Enumerations
enum adc_channel_t {
ADC_CHANNEL_0,
ADC_CHANNEL_1,
ADC_CHANNEL_2,
ADC_CHANNEL_3,
ADC_CHANNEL_4,
ADC_CHANNEL_5,
ADC_CHANNEL_6,
ADC_CHANNEL_7,
ADC_CHANNEL_NUM
 }
enum adc_ref_mode_t { ADC_REF_EXT = 0
 }
enum { ADC_BITS = 10
 }
Functions
void adc_reference_select (adc_ref_mode_t mode)
void adc_init (uint8_t channels)
bool adc_conversion_start (adc_channel_t channel)
bool adc_ready_p (void)
int8_t adc_read (adc_sample_t *value)
int8_t adc_read_wait (adc_channel_t channel, adc_sample_t *pvalue)
void adc_stop (void)
void adc_disable (void)
Detailed Description
Routines to use AT91 onboard ADC in polling mode.
Author: M. P. Hayes, UCECE
Date: 3 Feb 2005
Typedef Documentation
typedef uint16_t adc_sample_t
ADC sample size.
Enumeration Type Documentation
anonymous enum
ADC bits per conversion.
Enumerator:
ADC_BITS
enum adc_channel_t
ADC channels.
Enumerator:
ADC_CHANNEL_0
ADC_CHANNEL_1
ADC_CHANNEL_2
ADC_CHANNEL_3
ADC_CHANNEL_4
ADC_CHANNEL_5
ADC_CHANNEL_6
ADC_CHANNEL_7
ADC_CHANNEL_NUM
enum adc_ref_mode_t
ADC reference modes.
Enumerator:
ADC_REF_EXT
Function Documentation
bool adc_conversion_start (adc_channel_t channel)
Starts a conversion in the ADC on the specified channel.
References ADC_CHANNEL_NUM, adc_ready_p(), adc_start(), and AT91C_BASE_ADC.
Referenced by adc_read_wait().
void adc_disable (void)
Disables the ADC from doing anything. Requires reinitalisation.
Disables the ADC from doing anything.
void adc_init (uint8_t channels __UNUSED__)
Initalises the ADC registers for polling operation.
References adc_read_wait(), adc_reset(), and adc_resolution_set().
int8_t adc_read (adc_sample_t * pvalue)
Returns 1 if valid sample read.
References adc_ready_p(), and AT91C_BASE_ADC.
Referenced by adc_read_wait().
int8_t adc_read_wait (adc_channel_t channel, adc_sample_t * pvalue)
Start conversion on selected channel, wait until conversion finished.
References adc_conversion_start(), adc_read(), and adc_ready_p().
Referenced by adc_init().
bool adc_ready_p (void)
Returns true if a conversion is not in progress.
Returns true if a conversion has finished.
References AT91C_ADC_DRDY, and AT91C_BASE_ADC.
Referenced by adc_conversion_start(), adc_read(), and adc_read_wait().
void adc_reference_select (adc_ref_mode_t mode __UNUSED__)
Select ADC reference mode.
void adc_stop (void)
Halts any currently running conversion.