adc.c File Reference
Analogue to digital converter routines for AT91SAM7 processors.
#include `adc.h`
#include `bits.h`
Defines
#define ADC_8BIT_CLOCK_MAX 8e6
#define ADC_10BIT_CLOCK_MAX 5e6
#define ADC_STARTUP_TIME_MIN 20e-6
#define ADC_SAMPLE_TIME_MIN 600e-9
#define ADC_8BIT_CLOCK ADC_8BIT_CLOCK_MAX
#define ADC_10BIT_CLOCK ADC_10BIT_CLOCK_MAX
#define ADC_STARTUP_TIME ADC_STARTUP_TIME_MIN
#define ADC_SAMPLE_TIME ADC_SAMPLE_TIME_MIN
#define ADC_8BIT_PRESCALE ((uint8_t)(F_CPU / (2 * ADC_8BIT_CLOCK) + 0.5 - 1))
#define ADC_10BIT_PRESCALE ((uint8_t)(F_CPU / (2 * ADC_10BIT_CLOCK) + 0.5 - 1))
#define ADC_8BIT_CLOCK1 (F_CPU / ((ADC_8BIT_PRESCALE + 1) * 2))
#define ADC_10BIT_CLOCK1 (F_CPU / ((ADC_10BIT_PRESCALE + 1) * 2))
#define ADC_8BIT_STARTUP ((uint8_t)(ADC_STARTUP_TIME * ADC_8BIT_CLOCK1 / 8 + 0.5 - 1))
#define ADC_10BIT_STARTUP ((uint8_t)(ADC_STARTUP_TIME * ADC_10BIT_CLOCK1 / 8 +0.5 - 1))
#define ADC_8BIT_SHTIM ((uint8_t)(ADC_SAMPLE_TIME * ADC_8BIT_CLOCK1 + 0.5 - 1))
#define ADC_10BIT_SHTIM ((uint8_t)(ADC_SAMPLE_TIME * ADC_10BIT_CLOCK1 + 0.5 - 1))
Functions
static void adc_reset (void)
void adc_sleep (void)
static bool adc_resolution_set (uint8_t resolution)
static void adc_start (void)
void adc_reference_select (adc_ref_mode_t mode __UNUSED__)
void adc_init (uint8_t channels __UNUSED__)
bool adc_conversion_start (adc_channel_t channel)
bool adc_ready_p (void)
int8_t adc_read (adc_sample_t *pvalue)
int8_t adc_read_wait (adc_channel_t channel, adc_sample_t *pvalue)
void adc_stop (void)
void adc_disable (void)
Detailed Description
Analogue to digital converter routines for AT91SAM7 processors.
Author:
Date: 12 February 2008
Define Documentation
#define ADC_10BIT_CLOCK ADC_10BIT_CLOCK_MAX
#define ADC_10BIT_CLOCK1 (F_CPU / ((ADC_10BIT_PRESCALE + 1) * 2))
#define ADC_10BIT_CLOCK_MAX 5e6
#define ADC_10BIT_PRESCALE ((uint8_t)(F_CPU / (2 * ADC_10BIT_CLOCK) + 0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_10BIT_SHTIM ((uint8_t)(ADC_SAMPLE_TIME * ADC_10BIT_CLOCK1 + 0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_10BIT_STARTUP ((uint8_t)(ADC_STARTUP_TIME * ADC_10BIT_CLOCK1 / 8 +0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_8BIT_CLOCK ADC_8BIT_CLOCK_MAX
#define ADC_8BIT_CLOCK1 (F_CPU / ((ADC_8BIT_PRESCALE + 1) * 2))
#define ADC_8BIT_CLOCK_MAX 8e6
#define ADC_8BIT_PRESCALE ((uint8_t)(F_CPU / (2 * ADC_8BIT_CLOCK) + 0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_8BIT_SHTIM ((uint8_t)(ADC_SAMPLE_TIME * ADC_8BIT_CLOCK1 + 0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_8BIT_STARTUP ((uint8_t)(ADC_STARTUP_TIME * ADC_8BIT_CLOCK1 / 8 + 0.5 - 1))
Referenced by adc_resolution_set().
#define ADC_SAMPLE_TIME ADC_SAMPLE_TIME_MIN
#define ADC_SAMPLE_TIME_MIN 600e-9
#define ADC_STARTUP_TIME ADC_STARTUP_TIME_MIN
#define ADC_STARTUP_TIME_MIN 20e-6
Function Documentation
bool adc_conversion_start (adc_channel_t channel)
Starts a conversion in the ADC on the specified channel.
References ADC_CHANNEL_NUM, adc_ready_p(), adc_start(), and AT91C_BASE_ADC.
Referenced by adc_read_wait().
void adc_disable (void)
Disables the ADC from doing anything.
void adc_init (uint8_t channels __UNUSED__)
Initalises the ADC registers for polling operation.
References adc_read_wait(), adc_reset(), and adc_resolution_set().
int8_t adc_read (adc_sample_t * pvalue)
Returns 1 if valid sample read.
References adc_ready_p(), and AT91C_BASE_ADC.
Referenced by adc_read_wait().
int8_t adc_read_wait (adc_channel_t channel, adc_sample_t * pvalue)
Start conversion on selected channel, wait until conversion finished.
References adc_conversion_start(), adc_read(), and adc_ready_p().
Referenced by adc_init().
bool adc_ready_p (void)
Returns true if a conversion has finished.
References AT91C_ADC_DRDY, and AT91C_BASE_ADC.
Referenced by adc_conversion_start(), adc_read(), and adc_read_wait().
void adc_reference_select (adc_ref_mode_t mode __UNUSED__)
Select ADC reference mode.
static void adc_reset (void) [static]
References AT91C_ADC_SWRST, and AT91C_BASE_ADC.
Referenced by adc_init().
static bool adc_resolution_set (uint8_t resolution) [static]
References ADC_10BIT_PRESCALE, ADC_10BIT_SHTIM, ADC_10BIT_STARTUP, ADC_8BIT_PRESCALE, ADC_8BIT_SHTIM, ADC_8BIT_STARTUP, AT91C_ADC_LOWRES, AT91C_BASE_ADC, and BITS_INSERT.
Referenced by adc_init().
void adc_sleep (void)
References AT91C_ADC_SLEEP, and AT91C_BASE_ADC.
static void adc_start (void) [static]
References AT91C_ADC_START, and AT91C_BASE_ADC.
Referenced by adc_conversion_start().
void adc_stop (void)
Halts any currently running conversion.