cpu.h File Reference
#include `config.h`
#include `irq.h`
#include `bits.h`
Defines
#define CPU_FLASH_SPEED 30e6
#define CPU_FLASH_READ_CYCLES 1
#define CPU_MODE_MASK 0x1f
#define cpu_cpsr_c_set_const(cpsr) __asm__ (`\tmsr CPSR_c, %0` : : `i` (cpsr))
#define F_SLCK 32768
#define CPU_OS_DELAY 1.5e-3
#define CPU_OS_COUNT ((uint16_t) (CPU_OS_DELAY * F_SLCK + 7)) / 8
#define CPU_PLL_DELAY 0.9e-3
#define CPU_PLL_COUNT (uint16_t) (CPU_PLL_DELAY * F_SLCK)
#define CPU_USB_LOG2_DIV 0
Enumerations
enum arm_mode_t {
CPU_MODE_USR = 0x10,
CPU_MODE_FIQ = 0x11,
CPU_MODE_IRQ = 0x12,
CPU_MODE_SVC = 0x13,
CPU_MODE_ABT = 0x17,
CPU_MODE_UND = 0x1b,
CPU_MODE_SYS = 0x1f
 }
enum { CPU_T_BIT = BIT (5),
CPU_F_BIT = BIT (6),
CPU_I_BIT = BIT (7)
 }
Functions
__inline __attribute__ ((always_inline)) void cpu_sp_set(uint32_t val)
__inline void cpu_sram_remap (void)
__inline void cpu_sram_unremap (void)
__inline void cpu_watchdog_disable (void)
static void cpu_flash_init (void)
static void cpu_clock_init (void)
static void cpu_idle (void)
static void cpu_reset (void)
static void cpu_reset_enable (void)
static void cpu_reset_disable (void)
static uint8_t cpu_reset_type_get (void)
static bool cpu_brownout_detect_get (void)
static bool cpu_reset_detect_get (void)
void _irq_unexpected_handler (void)
void _irq_spurious_handler (void)
static void cpu_init (void)
static void cpu_sleep (void)
Define Documentation
#define cpu_cpsr_c_set_const(cpsr) __asm__ (`\tmsr CPSR_c, %0` : : `i` (cpsr))
Set the control bits, I, F, T, and M[4:0]. This only works for a constant argument.
Parameters:
CPSR control bit mask.
Referenced by _irq_handler(), _reset_handler(), and start().
#define CPU_FLASH_READ_CYCLES 1
Referenced by cpu_flash_init().
#define CPU_FLASH_SPEED 30e6
#define CPU_MODE_MASK 0x1f
#define CPU_OS_COUNT ((uint16_t) (CPU_OS_DELAY * F_SLCK + 7)) / 8
Referenced by cpu_clock_init().
#define CPU_OS_DELAY 1.5e-3
#define CPU_PLL_COUNT (uint16_t) (CPU_PLL_DELAY * F_SLCK)
Referenced by cpu_clock_init().
#define CPU_PLL_DELAY 0.9e-3
#define CPU_USB_LOG2_DIV 0
Referenced by cpu_clock_init().
#define F_SLCK 32768
Enumeration Type Documentation
anonymous enum
Current processor status register (CPSR) bits.
Enumerator:
CPU_T_BIT
CPU_F_BIT
 Thumb mode
CPU_I_BIT
 Disable FIQ interrupts
enum arm_mode_t
The ARM7 has 7 processor modes: user, system, supervisor, abort, undefined, interrupt, and fast interrupt. All except user mode are privileged modes and all except user and system modes are exception modes.
System mode is like user mode (it uses the user mode registers) but has full supervisor mode priviledges. System mode is usually switched from supervisor mode to access user mode registers, etc. Since system mode has full priviledges it is possible to switch back from system to supervisor mode. Once in user mode the only way the mode can be changed is with an interrupt.
User mode is typically used for user applications and supervisor mode is typically used by the operating system (kernel mode). Without memory management many operating systems (such as ecos) will use supervisor mode for everything to reduce the overhead of switching modes.
Each mode (except system) has their own banked copies of R13 (link register) and R14 (stack pointer) so there can be separate stacks for each mode. FIQ mode also has banked copies of R8--R12 for fast context switching.
Enumerator:
CPU_MODE_USR
CPU_MODE_FIQ
 User mode
CPU_MODE_IRQ
 Fast interrupt mode
CPU_MODE_SVC
 Interrupt mode
CPU_MODE_ABT
 Supervisor mode
CPU_MODE_UND
 Abort mode
CPU_MODE_SYS
 Undefined mode
Function Documentation
__inline __attribute__ ((always_inline))
Set the stack pointer of the current mode
Parameters:
stack pointer initial value.
Set the control bits, I, F, T, and M[4:0] of the CPSR.
Parameters:
CPSR control bit mask.
Set the flag bits of the CPSR.
Parameters:
CPSR flag bits mask.
Set all the fields of CPSR (note the s and x fields are currently unused).
Parameters:
CPSR.
Get the CPSR (all fields).
Returns: CPSR.
Set the mode bits M[4:0] of the CPSR.
Parameters:
CPSR mode bits mask.
Get the SPSR (all fields).
Returns: SPSR.
void _irq_spurious_handler (void)
Dummy ISR for spurious interrupts.
Referenced by cpu_init().
void _irq_unexpected_handler (void)
Dummy ISR for unexpected interrupts.
Referenced by cpu_init().
static bool cpu_brownout_detect_get (void) [static]
References AT91C_BASE_RSTC, and AT91C_RSTC_BODSTS.
static void cpu_clock_init (void) [static]
Set up the main clock (MAINCK), PLL clock, and master clock (MCK).
References AT91C_BASE_PMC, AT91C_CKGR_MOSCEN, AT91C_PMC_CSS_PLL_CLK, AT91C_PMC_LOCK, AT91C_PMC_MCKRDY, AT91C_PMC_MOSCS, AT91C_PMC_PRES_CLK_2, BITS, CPU_OS_COUNT, CPU_PLL_COUNT, and CPU_USB_LOG2_DIV.
static void cpu_flash_init (void) [static]
Initialise flash memory controller.
References AT91C_BASE_MC, AT91C_MC_FWS_0FWS, AT91C_MC_FWS_1FWS, AT91C_MC_FWS_2FWS, AT91C_MC_FWS_3FWS, BITS_INSERT, and CPU_FLASH_READ_CYCLES.
static void cpu_idle (void) [static]
References AT91C_BASE_PMC, and AT91C_PMC_PCK.
Referenced by cpu_sleep().
static void cpu_init (void) [static]
Initialise flash, disable watchdog, set up clocks.
References _irq_spurious_handler(), _irq_unexpected_handler(), AT91C_BASE_AIC, cpu_clock_init(), cpu_flash_init(), cpu_reset_enable(), cpu_sram_remap(), cpu_watchdog_disable(), IRQ_ID_MAX, IRQ_ID_MIN, and irq_vector_set().
static void cpu_reset (void) [static]
References AT91C_BASE_RSTC, AT91C_RSTC_PERRST, and AT91C_RSTC_PROCRST.
static bool cpu_reset_detect_get (void) [static]
References AT91C_BASE_RSTC, and AT91C_RSTC_URSTS.
static void cpu_reset_disable (void) [static]
References AT91C_BASE_RSTC, and AT91C_RSTC_URSTEN.
static void cpu_reset_enable (void) [static]
References AT91C_BASE_RSTC, and AT91C_RSTC_URSTEN.
Referenced by cpu_init().
static uint8_t cpu_reset_type_get (void) [static]
References AT91C_BASE_RSTC.
static void cpu_sleep (void) [static]
References cpu_idle().
__inline void cpu_sram_remap (void)
Remap SRAM that SRAM exists at 0x200000 as well as at 0x000000. On reset the Flash at 0x100000 is mapped to address 0x00000 as well as 0x100000. Note writing to the remap bit a second time toggles the remapping so that the Flash appears at address 0x000000. This causes problems if running from the debugger since theCPU is not reset. Thus we don't toggle the remap bit if the SRAM is already remapped.
References AT91C_BASE_MC, AT91C_ISRAM, and AT91C_MC_RCB.
Referenced by cpu_init().
__inline void cpu_sram_unremap (void)
Unremap SRAM.
References AT91C_BASE_MC, AT91C_ISRAM, and AT91C_MC_RCB.
__inline void cpu_watchdog_disable (void)
Disable watchdog.
References AT91C_BASE_WDTC, and AT91C_WDTC_WDDIS.
Referenced by cpu_init().