cpu.c File Reference
CPU routines for AT91SAM7 processors.
#include `config.h`
#include `cpu.h`
#include `irq.h`
Defines
#define F_SLCK 32768
#define OS_DELAY 1.5e-3
#define OS_COUNT ((uint16_t) (OS_DELAY * F_SLCK + 7)) / 8
#define PLL_DELAY 0.9e-3
#define PLL_COUNT (uint16_t) (PLL_DELAY * F_SLCK)
#define USB_LOG2_DIV 0
Functions
static void cpu_flash_init (void)
static void cpu_clock_init (void)
static void cpu_dummy_isr (void)
void cpu_init (void)
Detailed Description
CPU routines for AT91SAM7 processors.
Author: M. P. Hayes, UCECE
Date: 04 June 2007
Define Documentation
#define F_SLCK 32768
#define OS_COUNT ((uint16_t) (OS_DELAY * F_SLCK + 7)) / 8
Referenced by cpu_clock_init().
#define OS_DELAY 1.5e-3
#define PLL_COUNT (uint16_t) (PLL_DELAY * F_SLCK)
Referenced by cpu_clock_init().
#define PLL_DELAY 0.9e-3
#define USB_LOG2_DIV 0
Referenced by cpu_clock_init().
Function Documentation
static void cpu_clock_init (void) [static]
Set up the main clock (MAINCK), PLL clock, and master clock (MCK).
References AT91C_BASE_PMC, AT91C_CKGR_MOSCEN, AT91C_PMC_CSS_PLL_CLK, AT91C_PMC_LOCK, AT91C_PMC_MCKRDY, AT91C_PMC_MOSCS, AT91C_PMC_PRES_CLK_2, BITS, OS_COUNT, PLL_COUNT, and USB_LOG2_DIV.
Referenced by cpu_init().
static void cpu_dummy_isr (void) [static]
Dummy ISR for unexpected interrupts.
Referenced by cpu_init().
static void cpu_flash_init (void) [static]
Initialise flash memory controller.
References AT91C_BASE_MC, AT91C_MC_FWS_1FWS, and BITS_INSERT.
Referenced by cpu_init().
void cpu_init (void)
Initialise flash, disable watchdog, set up clocks.
References AT91C_BASE_AIC, cpu_clock_init(), cpu_dummy_isr(), cpu_flash_init(), cpu_sram_remap(), cpu_watchdog_disable(), IRQ_ID_MAX, IRQ_ID_MIN, and irq_vector_set().
Referenced by _reset_handler().