crt0.c File Reference
C run time initialisation for the Atmel AT91 series of ARM7 TDMI microprocessors.
#include `config.h`
#include `cpu.h`
Defines
#define IRQ_STACK_SIZE (3 * 8 * 4)
#define AIC_FVR_OFFSET 264
#define AIC_IVR_OFFSET 260
Functions
int main (int, char *)
void exit (int status __attribute((unused)))
void start (void)
void _reset_handler (void)
void _irq_handler (void)
void _irq_unexpected_handler (void)
void _irq_spurious_handler (void)
Variables
char _stack
char _data
char _edata
char _etext
char __bss_start__
char __bss_end__
Detailed Description
C run time initialisation for the Atmel AT91 series of ARM7 TDMI microprocessors.
Author: M. P. Hayes, UCECE
Date: 10 June 2007
Define Documentation
#define AIC_FVR_OFFSET 264
#define AIC_IVR_OFFSET 260
#define IRQ_STACK_SIZE (3 * 8 * 4)
Function Documentation
void _irq_handler (void)
IRQ handler. This must run in ARM mode. Note this will not compile in Thumb mode because of some of the inline ARM assembler instructions.
References AIC_IVR_OFFSET, AT91C_BASE_AIC, cpu_cpsr_c_set_const, CPU_I_BIT, CPU_MODE_IRQ, and CPU_MODE_SVC.
void _irq_spurious_handler (void)
Dummy ISR for spurious interrupts.
Referenced by cpu_init().
void _irq_unexpected_handler (void)
Dummy ISR for unexpected interrupts.
void _reset_handler (void)
References __bss_end__, __bss_start__, _data, _edata, _etext, _stack, AT91C_BASE_AIC, cpu_cpsr_c_set_const, CPU_F_BIT, CPU_I_BIT, cpu_init(), CPU_MODE_FIQ, CPU_MODE_IRQ, CPU_MODE_SVC, exit(), IRQ_STACK_SIZE, and main().
void exit (int status __attribute(unused))
int main (int, char *)
End of uninitialised variables.
void start (void)
Startup function.
References AIC_FVR_OFFSET, cpu_cpsr_c_set_const, CPU_F_BIT, CPU_I_BIT, CPU_MODE_FIQ, and CPU_MODE_SVC.
Variable Documentation
char __bss_end__
Start of uninitialised variables.
char __bss_start__
Start of initial values.
char _data
Top of stack.
char _edata
Start of initialised variables.
char _etext
End of initialised variables.
char _stack
Symbols defined by linker script.