pwm.c File Reference
Pulse Width Modulation routines for AT91SAM7 processors.
#include `pwm.h`
#include `bits.h`
Functions
static AT91S_PWMC_CH * pwm_base (pwm_channel_t channel)
uint8_t pwm_init (void)
uint8_t pwm_config (pwm_channel_t channel, uint16_t period, uint16_t duty, pwm_align_t alignment, pwm_polarity_t polarity)
void pwm_start (pwm_channel_mask_t channel_mask)
void pwm_stop (pwm_channel_mask_t channel_mask)
void pwm_enable (pwm_channel_t channel)
void pwm_disable (pwm_channel_t channel)
uint8_t pwm_update (pwm_channel_t channel, uint16_t new_period, uint16_t new_duty)
Detailed Description
Pulse Width Modulation routines for AT91SAM7 processors.
Author:
Date: 12 February 2008
Function Documentation
static AT91S_PWMC_CH* pwm_base (pwm_channel_t channel) [static]
References AT91C_BASE_PWMC_CH0, AT91C_BASE_PWMC_CH1, AT91C_BASE_PWMC_CH2, AT91C_BASE_PWMC_CH3, PWM_CHANNEL_0, PWM_CHANNEL_1, PWM_CHANNEL_2, and PWM_CHANNEL_3.
Referenced by pwm_config(), and pwm_update().
uint8_t pwm_config (pwm_channel_t channel, uint16_t period, uint16_t duty, pwm_align_t alignment, pwm_polarity_t polarity)
References BITS_INSERT, pwm_base(), _AT91S_PWMC_CH::PWMC_CDTYR, _AT91S_PWMC_CH::PWMC_CMR, and _AT91S_PWMC_CH::PWMC_CPRDR.
void pwm_disable (pwm_channel_t channel)
References AT91C_BASE_PIOA, AT91C_PA0_PWM0, AT91C_PA11_PWM0, AT91C_PA12_PWM1, AT91C_PA13_PWM2, AT91C_PA14_PWM3, AT91C_PA1_PWM1, AT91C_PA23_PWM0, AT91C_PA24_PWM1, AT91C_PA25_PWM2, AT91C_PA2_PWM2, and AT91C_PA7_PWM3.
void pwm_enable (pwm_channel_t channel)
References AT91C_BASE_PIOA, AT91C_PA0_PWM0, AT91C_PA11_PWM0, AT91C_PA12_PWM1, AT91C_PA13_PWM2, AT91C_PA14_PWM3, AT91C_PA1_PWM1, AT91C_PA23_PWM0, AT91C_PA24_PWM1, AT91C_PA25_PWM2, AT91C_PA2_PWM2, and AT91C_PA7_PWM3.
uint8_t pwm_init (void)
References AT91C_BASE_PMC, and AT91C_ID_PWMC.
void pwm_start (pwm_channel_mask_t channel_mask)
References AT91C_BASE_PWMC.
void pwm_stop (pwm_channel_mask_t channel_mask)
References AT91C_BASE_PWMC.
uint8_t pwm_update (pwm_channel_t channel, uint16_t new_period, uint16_t new_duty)
References AT91C_BASE_PWMC, BITS_EXTRACT, BITS_INSERT, pwm_base(), _AT91S_PWMC_CH::PWMC_CMR, and _AT91S_PWMC_CH::PWMC_CUPDR.