spi.c File Reference
Routines for interfacing to the SPI bus.
#include `config.h`
#include `spi.h`
#include `bits.h`
Defines
#define SPI_CHANNEL_DEFAULT SPI_CHANNEL0
#define HOSTED 0
#define SPI_XFER(txdata, rxdata)
Enumerations
enum { SPI_NCPHA_MASK = 0x02,
SPI_CPOL_MASK = 0x01
 }
Functions
static uint32_t spi_channel_csr_get (spi_channel_t channel)
static void spi_channel_csr_set (spi_channel_t channel, uint32_t csr)
static void spi_channel_delay_set (spi_channel_t channel, uint16_t delay)
static void spi_channel_clock_delay_set (spi_channel_t channel, uint16_t delay)
static void spi_channel_divisor_set (spi_channel_t channel, spi_clock_divisor_t clock_divisor)
static void spi_channel_bits_set (spi_channel_t channel, uint8_t bits)
static void spi_channel_mode_set (spi_channel_t channel, spi_mode_t mode)
static bool spi_channel_cs_enable (spi_channel_t channel)
static bool spi_channel_cs_disable (spi_channel_t channel)
void spi_delay_set (uint16_t clock_divisor)
void spi_divisor_set (spi_clock_divisor_t clock_divisor)
void spi_clock_delay_set (uint16_t delay)
static void spi_csr_set (uint32_t csr)
static uint32_t spi_csr_get (void)
void spi_bits_set (uint8_t bits)
void spi_reset (void)
void spi_enable (void)
void spi_disable (void)
void spi_mode_set (spi_mode_t mode)
void spi_multichannel_select (void)
void spi_multichannel_deselect (void)
void spi_channel_select (spi_channel_t channel)
void spi_channel_deselect (spi_channel_t channel __UNUSED__)
bool spi_cs_enable (void)
bool spi_cs_disable (void)
void spi_init (void)
void spi_shutdown (void)
bool spi_read_ready_p (void)
uint8_t spi_getc (void)
bool spi_write_ready_p (void)
void spi_putc (char ch)
uint8_t spi_xferc (char ch)
void spi_puts (const char *str)
uint16_t spi_get16 (void)
void spi_put16 (uint16_t data)
uint16_t spi_xfer16 (uint16_t data)
uint32_t spi_get32 (void)
void spi_put32 (uint32_t data)
uint32_t spi_xfer32 (uint32_t data)
Variables
static uint8_t spi_channel = SPI_CHANNEL_DEFAULT
static uint8_t spi_init_count = 0
Detailed Description
Routines for interfacing to the SPI bus.
Author: Michael Hayes
Date: 30 July 2007
Define Documentation
#define HOSTED 0
#define SPI_CHANNEL_DEFAULT SPI_CHANNEL0
Referenced by spi_channel_deselect(), spi_init(), and spi_multichannel_deselect().
#define SPI_XFER(txdata, rxdata)
Value:
do                                                                  \
    {                                                                   \
        AT91S_SPI *pSPI = AT91C_BASE_SPI;                               \
                                                                        \
        /* Write data to TDR.  */                                       \
        pSPI->SPI_TDR = (txdata);                                       \
                                                                        \
        /* Wait until spi port finishes transmitting/receiving.  */     \
        while (!SPI_READY_P())                                          \
            continue;                                                   \
                                                                        \
        /* Read new data from RDR (this clears RDRF).  */               \
        (rxdata) = pSPI->SPI_RDR;                                       \
                                                                        \
    } while (0)
Referenced by spi_get16(), spi_get32(), spi_getc(), spi_put16(), spi_put32(), spi_putc(), spi_puts(), spi_xfer16(), spi_xfer32(), and spi_xferc().
Enumeration Type Documentation
anonymous enum
Enumerator:
SPI_NCPHA_MASK
SPI_CPOL_MASK
Function Documentation
void spi_bits_set (uint8_t bits)
References spi_channel, and spi_channel_bits_set().
Referenced by spi_init().
static void spi_channel_bits_set (spi_channel_t channel, uint8_t bits) [static]
References BITS_INSERT, spi_channel_csr_get(), and spi_channel_csr_set().
Referenced by spi_bits_set().
static void spi_channel_clock_delay_set (spi_channel_t channel, uint16_t delay) [static]
Set the delay (in clocks) before the clock starts.
References BITS_INSERT, spi_channel_csr_get(), and spi_channel_csr_set().
Referenced by spi_clock_delay_set().
static bool spi_channel_cs_disable (spi_channel_t channel) [static]
References AT91C_PA10_NPCS2, AT91C_PA11_NPCS0, AT91C_PA22_NPCS3, AT91C_PA30_NPCS2, AT91C_PA31_NPCS1, AT91C_PA3_NPCS3, AT91C_PA5_NPCS3, AT91C_PA9_NPCS1, and AT91C_PIOA_PER.
Referenced by spi_cs_disable().
static bool spi_channel_cs_enable (spi_channel_t channel) [static]
References AT91C_PA10_NPCS2, AT91C_PA11_NPCS0, AT91C_PA22_NPCS3, AT91C_PA30_NPCS2, AT91C_PA31_NPCS1, AT91C_PA3_NPCS3, AT91C_PA5_NPCS3, AT91C_PA9_NPCS1, AT91C_PIOA_ASR, AT91C_PIOA_BSR, and AT91C_PIOA_PDR.
Referenced by spi_cs_enable().
static uint32_t spi_channel_csr_get (spi_channel_t channel) [static]
References AT91C_BASE_SPI, and _AT91S_SPI::SPI_CSR.
Referenced by spi_channel_bits_set(), spi_channel_clock_delay_set(), spi_channel_delay_set(), spi_channel_divisor_set(), spi_channel_mode_set(), and spi_csr_get().
static void spi_channel_csr_set (spi_channel_t channel, uint32_t csr) [static]
References AT91C_BASE_SPI, and _AT91S_SPI::SPI_CSR.
Referenced by spi_channel_bits_set(), spi_channel_clock_delay_set(), spi_channel_delay_set(), spi_channel_divisor_set(), spi_channel_mode_set(), and spi_csr_set().
static void spi_channel_delay_set (spi_channel_t channel, uint16_t delay) [static]
Set the delay (in clocks * 32) before starting a transmission on same SPI channel. The default is 0.
References BITS_INSERT, spi_channel_csr_get(), and spi_channel_csr_set().
Referenced by spi_delay_set().
void spi_channel_deselect (spi_channel_t channel __UNUSED__)
References SPI_CHANNEL_DEFAULT, and spi_channel_select().
static void spi_channel_divisor_set (spi_channel_t channel, spi_clock_divisor_t clock_divisor) [static]
The minimum divisor value is 1, this gives the maximum rate of MCK.
References BITS_INSERT, spi_channel_csr_get(), and spi_channel_csr_set().
Referenced by spi_divisor_set().
static void spi_channel_mode_set (spi_channel_t channel, spi_mode_t mode) [static]
References spi_channel_csr_get(), spi_channel_csr_set(), SPI_CPOL_MASK, SPI_MODE_0, SPI_MODE_1, SPI_MODE_2, SPI_MODE_3, and SPI_NCPHA_MASK.
Referenced by spi_mode_set().
void spi_channel_select (spi_channel_t channel)
References AT91C_BASE_SPI, AT91C_SPI_PS_VARIABLE, BITS_INSERT, spi_channel, SPI_CHANNEL_MASK, and _AT91S_SPI::SPI_MR.
Referenced by spi_channel_deselect(), spi_init(), and spi_multichannel_deselect().
void spi_clock_delay_set (uint16_t delay)
Set the delay (in clocks) before the clock starts.
References spi_channel, and spi_channel_clock_delay_set().
bool spi_cs_disable (void)
Disable the chip select; this does not drive it.
References spi_channel, and spi_channel_cs_disable().
bool spi_cs_enable (void)
Enable the chip select; this does not drive it. SPI_CSX_BIT needs to be defined to use channel X, X = 0..3 SPI_CHANNEL0_CS_BIT 11 SPI_CHANNEL1_CS_BIT 9 or 31 SPI_CHANNEL2_CS_BIT 10 or 30 SPI_CHANNEL3_CS_BIT 3, 5, or 22
References spi_channel, and spi_channel_cs_enable().
static uint32_t spi_csr_get (void) [static]
References spi_channel, and spi_channel_csr_get().
static void spi_csr_set (uint32_t csr) [static]
References spi_channel, and spi_channel_csr_set().
Referenced by spi_init().
void spi_delay_set (uint16_t clock_divisor)
Set the delay (in clocks * 32) before starting a transmission on same SPI channel. The default is 0.
References spi_channel, and spi_channel_delay_set().
void spi_disable (void)
References AT91C_BASE_SPI, AT91C_SPI_SPIDIS, and _AT91S_SPI::SPI_CR.
Referenced by spi_shutdown().
void spi_divisor_set (spi_clock_divisor_t clock_divisor)
References spi_channel, and spi_channel_divisor_set().
Referenced by spi_init().
void spi_enable (void)
References AT91C_BASE_SPI, AT91C_SPI_SPIEN, and _AT91S_SPI::SPI_CR.
Referenced by spi_init().
uint16_t spi_get16 (void)
References SPI_XFER.
uint32_t spi_get32 (void)
References SPI_XFER.
uint8_t spi_getc (void)
References SPI_XFER.
void spi_init (void)
Initialise SPI for master mode.
References AT91C_BASE_PMC, AT91C_BASE_SPI, AT91C_ID_SPI, AT91C_PA12_MISO, AT91C_PA13_MOSI, AT91C_PA14_SPCK, AT91C_PIOA_ASR, AT91C_PIOA_PDR, AT91C_PIOA_PPUDR, AT91C_SPI_MODFDIS, AT91C_SPI_MSTR, spi_bits_set(), SPI_CHANNEL_DEFAULT, spi_channel_select(), spi_csr_set(), spi_divisor_set(), spi_enable(), spi_init_count, SPI_MODE_0, spi_mode_set(), _AT91S_SPI::SPI_MR, and spi_reset().
void spi_mode_set (spi_mode_t mode)
References spi_channel, and spi_channel_mode_set().
Referenced by spi_init().
void spi_multichannel_deselect (void)
Enable fixed peripheral select and switch to default channel.
References SPI_CHANNEL_DEFAULT, and spi_channel_select().
void spi_multichannel_select (void)
Enable variable peripheral select.
References AT91C_BASE_SPI, AT91C_SPI_PS_VARIABLE, and _AT91S_SPI::SPI_MR.
void spi_put16 (uint16_t data)
References SPI_XFER.
Referenced by mspi_write().
void spi_put32 (uint32_t data)
References SPI_XFER.
void spi_putc (char ch)
References SPI_XFER.
Referenced by mspi_write().
void spi_puts (const char * str)
References SPI_XFER.
bool spi_read_ready_p (void)
References SPI_READY_P.
void spi_reset (void)
References AT91C_BASE_SPI, AT91C_SPI_SWRST, and _AT91S_SPI::SPI_CR.
Referenced by spi_init().
void spi_shutdown (void)
References AT91C_BASE_PMC, AT91C_ID_SPI, AT91C_PA12_MISO, AT91C_PA13_MOSI, AT91C_PA14_SPCK, AT91C_PIOA_CODR, AT91C_PIOA_PER, AT91C_PIOA_PPUDR, spi_disable(), and spi_init_count.
bool spi_write_ready_p (void)
References SPI_READY_P.
uint16_t spi_xfer16 (uint16_t data)
References SPI_XFER.
uint32_t spi_xfer32 (uint32_t data)
References SPI_XFER.
uint8_t spi_xferc (char ch)
References SPI_XFER.
Variable Documentation
uint8_t spi_channel = SPI_CHANNEL_DEFAULT [static]
Referenced by spi_bits_set(), spi_channel_select(), spi_clock_delay_set(), spi_cs_disable(), spi_cs_enable(), spi_csr_get(), spi_csr_set(), spi_delay_set(), spi_divisor_set(), and spi_mode_set().
uint8_t spi_init_count = 0 [static]
Referenced by spi_init(), and spi_shutdown().