spi_dma.c File Reference
Routines for interfacing to the SPI bus with DMA access.
#include `spi.h`
#include `spi_dma.h`
#include `config.h`
#include `bits.h`
Functions
bool spi_dma_write_finished_p (void)
bool spi_dma_read_finished_p (void)
bool spi_dma_write_enable_p (void)
bool spi_dma_read_enable_p (void)
void spi_dma_write_enable (void)
void spi_dma_write_disable (void)
void spi_dma_read_enable (void)
void spi_dma_read_disable (void)
void spi_dma_write_init (void *address, uint16_t size)
void spi_dma_read_init (void *address, uint16_t size)
Detailed Description
Routines for interfacing to the SPI bus with DMA access.
Author: Michael Hayes
Date: 18 December 2007
Function Documentation
void spi_dma_read_disable (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_RXTDIS, and _AT91S_PDC::PDC_PTCR.
Referenced by spi_dma_read_init().
void spi_dma_read_enable (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_RXTEN, and _AT91S_PDC::PDC_PTCR.
Referenced by spi_dma_read_init().
bool spi_dma_read_enable_p (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_RXTEN, and _AT91S_PDC::PDC_PTCR.
bool spi_dma_read_finished_p (void)
References AT91C_BASE_SPI, and AT91C_SPI_ENDRX.
void spi_dma_read_init (void * address, uint16_t size)
References AT91C_BASE_PDC_SPI, _AT91S_PDC::PDC_RCR, _AT91S_PDC::PDC_RNCR, _AT91S_PDC::PDC_RNPR, _AT91S_PDC::PDC_RPR, spi_dma_read_disable(), and spi_dma_read_enable().
void spi_dma_write_disable (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_TXTDIS, and _AT91S_PDC::PDC_PTCR.
Referenced by spi_dma_write_init().
void spi_dma_write_enable (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_TXTEN, and _AT91S_PDC::PDC_PTCR.
Referenced by spi_dma_write_init().
bool spi_dma_write_enable_p (void)
References AT91C_BASE_PDC_SPI, AT91C_PDC_TXTEN, and _AT91S_PDC::PDC_PTCR.
bool spi_dma_write_finished_p (void)
References AT91C_BASE_SPI, and AT91C_SPI_ENDTX.
void spi_dma_write_init (void * address, uint16_t size)
References AT91C_BASE_PDC_SPI, _AT91S_PDC::PDC_TCR, _AT91S_PDC::PDC_TNCR, _AT91S_PDC::PDC_TNPR, _AT91S_PDC::PDC_TPR, spi_dma_write_disable(), and spi_dma_write_enable().