spi.h File Reference
Routines for interfacing to the SPI bus.
#include `config.h`
Defines
#define SPI_READY_P() (AT91C_BASE_SPI $\rightarrow$ SPI_SR & AT91C_SPI_RDRF)
#define SPI_TXEMPTY_P() (AT91C_BASE_SPI $\rightarrow$ SPI_SR & AT91C_SPI_TXEMPTY)
#define SPI_CHANNEL_MASK(channel) (0x0f ^ BIT (channel))
#define spi_data_order_set(data_order)
Typedefs
typedef uint8_t spi_channel_t
typedef uint16_t spi_clock_divisor_t
Enumerations
enum { SPI_CHANNEL0 = 0,
SPI_CHANNEL1,
SPI_CHANNEL2,
SPI_CHANNEL3
 }
enum spi_mode_t { SPI_MODE_0 = 0,
SPI_MODE_1 = 1,
SPI_MODE_2 = 2,
SPI_MODE_3 = 3
 }
enum spi_data_order_t { SPI_DATA_MSB_FIRST = 0,
SPI_DATA_LSB_FIRST = 1
 }
Functions
void spi_init (void)
void spi_shutdown (void)
bool spi_cs_enable (void)
bool spi_cs_disable (void)
bool spi_read_ready_p (void)
uint8_t spi_getc (void)
bool spi_write_ready_p (void)
void spi_putc (char ch)
uint8_t spi_xferc (char ch)
void spi_puts (const char *str)
void spi_bits_set (uint8_t bits)
void spi_mode_set (spi_mode_t spi_mode)
void spi_multichannel_select (void)
void spi_multichannel_deselect (void)
void spi_channel_select (spi_channel_t channel)
void spi_channel_deselect (spi_channel_t channel)
void spi_clock_delay_set (uint16_t delay)
void spi_delay_set (uint16_t delay)
void spi_divisor_set (spi_clock_divisor_t clock_divisor)
uint16_t spi_get16 (void)
void spi_put16 (uint16_t data)
uint16_t spi_xfer16 (uint16_t data)
uint32_t spi_get32 (void)
void spi_put32 (uint32_t data)
uint32_t spi_xfer32 (uint32_t data)
Detailed Description
Routines for interfacing to the SPI bus.
Author: Michael Hayes
Date: 30 July 2007
Define Documentation
#define SPI_CHANNEL_MASK(channel) (0x0f ^ BIT (channel))
Referenced by spi_channel_select().
#define spi_data_order_set(data_order)
#define SPI_READY_P() (AT91C_BASE_SPI $\rightarrow$ SPI_SR & AT91C_SPI_RDRF)
Referenced by spi_read_ready_p(), and spi_write_ready_p().
#define SPI_TXEMPTY_P() (AT91C_BASE_SPI $\rightarrow$ SPI_SR & AT91C_SPI_TXEMPTY)
Typedef Documentation
typedef uint8_t spi_channel_t
typedef uint16_t spi_clock_divisor_t
Enumeration Type Documentation
anonymous enum
Enumerator:
SPI_CHANNEL0
SPI_CHANNEL1
SPI_CHANNEL2
SPI_CHANNEL3
enum spi_data_order_t
Enumerator:
SPI_DATA_MSB_FIRST
SPI_DATA_LSB_FIRST
enum spi_mode_t
Enumerator:
SPI_MODE_0
SPI_MODE_1
SPI_MODE_2
SPI_MODE_3
Function Documentation
void spi_bits_set (uint8_t bits)
References spi_channel, and spi_channel_bits_set().
Referenced by spi_init().
void spi_channel_deselect (spi_channel_t channel)
References SPI_CHANNEL_DEFAULT, and spi_channel_select().
void spi_channel_select (spi_channel_t channel)
References AT91C_BASE_SPI, AT91C_SPI_PS_VARIABLE, BITS_INSERT, spi_channel, SPI_CHANNEL_MASK, and _AT91S_SPI::SPI_MR.
Referenced by spi_channel_deselect(), spi_init(), and spi_multichannel_deselect().
void spi_clock_delay_set (uint16_t delay)
Set the delay (in clocks) before the clock starts.
References spi_channel, and spi_channel_clock_delay_set().
bool spi_cs_disable (void)
Disable the chip select; this does not drive it.
References spi_channel, and spi_channel_cs_disable().
bool spi_cs_enable (void)
Enable the chip select; this does not drive it. SPI_CSX_BIT needs to be defined to use channel X, X = 0..3 SPI_CHANNEL0_CS_BIT 11 SPI_CHANNEL1_CS_BIT 9 or 31 SPI_CHANNEL2_CS_BIT 10 or 30 SPI_CHANNEL3_CS_BIT 3, 5, or 22
References spi_channel, and spi_channel_cs_enable().
void spi_delay_set (uint16_t clock_divisor)
Set the delay (in clocks * 32) before starting a transmission on same SPI channel. The default is 0.
References spi_channel, and spi_channel_delay_set().
void spi_divisor_set (spi_clock_divisor_t clock_divisor)
References spi_channel, and spi_channel_divisor_set().
Referenced by spi_init().
uint16_t spi_get16 (void)
References SPI_XFER.
uint32_t spi_get32 (void)
References SPI_XFER.
uint8_t spi_getc (void)
References SPI_XFER.
void spi_init (void)
Initialise SPI for master mode.
References AT91C_BASE_PMC, AT91C_BASE_SPI, AT91C_ID_SPI, AT91C_PA12_MISO, AT91C_PA13_MOSI, AT91C_PA14_SPCK, AT91C_PIOA_ASR, AT91C_PIOA_PDR, AT91C_PIOA_PPUDR, AT91C_SPI_MODFDIS, AT91C_SPI_MSTR, spi_bits_set(), SPI_CHANNEL_DEFAULT, spi_channel_select(), spi_csr_set(), spi_divisor_set(), spi_enable(), spi_init_count, SPI_MODE_0, spi_mode_set(), _AT91S_SPI::SPI_MR, and spi_reset().
void spi_mode_set (spi_mode_t spi_mode)
References spi_channel, and spi_channel_mode_set().
Referenced by spi_init().
void spi_multichannel_deselect (void)
Enable fixed peripheral select and switch to default channel.
References SPI_CHANNEL_DEFAULT, and spi_channel_select().
void spi_multichannel_select (void)
Enable variable peripheral select.
References AT91C_BASE_SPI, AT91C_SPI_PS_VARIABLE, and _AT91S_SPI::SPI_MR.
void spi_put16 (uint16_t data)
References SPI_XFER.
Referenced by mspi_write().
void spi_put32 (uint32_t data)
References SPI_XFER.
void spi_putc (char ch)
References SPI_XFER.
Referenced by mspi_write().
void spi_puts (const char * str)
References SPI_XFER.
bool spi_read_ready_p (void)
References SPI_READY_P.
void spi_shutdown (void)
References AT91C_BASE_PMC, AT91C_ID_SPI, AT91C_PA12_MISO, AT91C_PA13_MOSI, AT91C_PA14_SPCK, AT91C_PIOA_CODR, AT91C_PIOA_PER, AT91C_PIOA_PPUDR, spi_disable(), and spi_init_count.
bool spi_write_ready_p (void)
References SPI_READY_P.
uint16_t spi_xfer16 (uint16_t data)
References SPI_XFER.
uint32_t spi_xfer32 (uint32_t data)
References SPI_XFER.
uint8_t spi_xferc (char ch)
References SPI_XFER.