syscalls.c File Reference
This file contains a collection of stub functions to replace those used by the C library newlib. Primarily, it provides functionality to redirect standard I/O.
#include `config.h`
#include <errno.h>
#include <unistd.h>
Functions
void stdio_redirect (void(*putc1)(int ch), int(*getc1)(void))
int _read (int file __UNUSED__, char *ptr __UNUSED__, int len __UNUSED__)
int _lseek (int file __UNUSED__, int ptr __UNUSED__, int dir __UNUSED__)
int _write (int file __UNUSED__, char *buffer, int size)
int _open (const char *path __UNUSED__, int flags __UNUSED__,...)
int _close (int file __UNUSED__)
int _kill (int pid __UNUSED__, int sig __UNUSED__)
void _exit (int status __UNUSED__)
int _getpid (int n __UNUSED__)
caddr_t _sbrk (int incr)
int _fstat (int file __UNUSED__, void *st __UNUSED__)
int _stat (const char *fname __UNUSED__, void *st __UNUSED__)
int _link (void)
int _unlink (const char *path __UNUSED__)
void _raise (void)
int _gettimeofday (void *tp __UNUSED__, void *tzp __UNUSED__)
clock_t _times (void *tp __UNUSED__)
int isatty (int fd)
int _system (const char *s __UNUSED__)
int _rename (const char *oldpath __UNUSED__, const char *newpath __UNUSED__)
Variables
static void(* stdio_putc)(int ch)=0
static int(* stdio_getc)(void)=0
Detailed Description
This file contains a collection of stub functions to replace those used by the C library newlib. Primarily, it provides functionality to redirect standard I/O.
Author: Michael Hayes
Date: 18 February 2008
Function Documentation
int _close (int file __UNUSED__)
void _exit (int status __UNUSED__)
int _fstat (int file __UNUSED__, void *st __UNUSED__)
int _getpid (int n __UNUSED__)
int _gettimeofday (void *tp __UNUSED__, void *tzp __UNUSED__)
int _kill (int pid __UNUSED__, int sig __UNUSED__)
int _link (void)
int _lseek (int file __UNUSED__, int ptr __UNUSED__, int dir __UNUSED__)
int _open (const char *path __UNUSED__, int flags __UNUSED__, ...)
void _raise (void)
int _read (int file __UNUSED__, char *ptr __UNUSED__, int len __UNUSED__)
int _rename (const char *oldpath __UNUSED__, const char *newpath __UNUSED__)
caddr_t _sbrk (int incr)
int _stat (const char *fname __UNUSED__, void *st __UNUSED__)
int _system (const char *s __UNUSED__)
clock_t _times (void *tp __UNUSED__)
int _unlink (const char *path __UNUSED__)
int _write (int file __UNUSED__, char * buffer, int size)
References stdio_putc.
int isatty (int fd)
void stdio_redirect (void(*)(int ch) putc1, int(*)(void) getc1)
References stdio_getc, and stdio_putc.
Variable Documentation
int(* stdio_getc)(void)=0 [static]
Referenced by stdio_redirect().
void(* stdio_putc)(int ch)=0 [static]
Referenced by _write(), and stdio_redirect().