tick.c File Reference
#include `pit.h`
#include `tick.h`
Functions
void tick_init (uint32_t divisor)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 15 May 2007
Function Documentation
void tick_init (uint32_t divisor)
References pit_init(), pit_period_set(), and pit_start().