tick.h File Reference
#include `config.h`
#include `pit.h`
Defines
#define TICK_RATE_MIN (F_CPU / 16 / (1 << 20))
#define TICK_DIVISOR(FREQ) PIT_DIVISOR (FREQ)
#define TICK_READY_P() PIT_COMPARE_P ()
#define TICK_WAIT() while (!TICK_READY_P ()) continue
#define TICK_RESET() PIT_RESET()
#define TICK_INT_ENABLE() PIT_INT_ENABLE()
#define TICK_INT_DISABLE() PIT_INT_DISABLE()
Functions
void tick_init (uint32_t divisor)
static void tick_wait (void)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 3 June 2007
Define Documentation
#define TICK_DIVISOR(FREQ) PIT_DIVISOR (FREQ)
#define TICK_INT_DISABLE() PIT_INT_DISABLE()
#define TICK_INT_ENABLE() PIT_INT_ENABLE()
#define TICK_RATE_MIN (F_CPU / 16 / (1 << 20))
#define TICK_READY_P() PIT_COMPARE_P ()
#define TICK_RESET() PIT_RESET()
#define TICK_WAIT() while (!TICK_READY_P ()) continue
Referenced by tick_wait().
Function Documentation
void tick_init (uint32_t divisor)
References pit_init(), pit_period_set(), and pit_start().
static void tick_wait (void) [static]
References TICK_WAIT.