timer.c File Reference
Timer counter routines for AT91SAM7 processors.
#include `timer.h`
#include `bits.h`
Defines
#define TIMER_CHANNEL_0 0
#define TIMER_CHANNEL_1 1
#define TIMER_CHANNEL_2 2
#define EX_TRG_NONE 0
#define EX_TRG_RISING 1
#define EX_TRG_FALLING 2
#define EX_TRG_EACH 3
#define EX_TRG_TIOB 0
#define EX_TRG_TIOA 1
#define RC_COMP_NONE 0
#define RC_COMP_TRG 1
#define LDRA_TIOA_NONE 0
#define LDRA_TIOA_RISING 1
#define LDRA_TIOA_FALLING 2
#define LDRA_TIOA_EACH 3
#define LDRB_TIOA_NONE 0
#define LDRB_TIOA_RISING 1
#define LDRB_TIOA_FALLING 2
#define LDRB_TIOA_EACH 3
#define LDRB_CLK_NONE 0
#define LDRB_CLK_STOP 1
#define LDRB_CLK_DIS 2
#define LDRB_CLK_STOP_DIS 3
#define TIMER_TC_CV 0
#define TIMER_TC_RA 1
#define TIMER_TC_RB 2
#define TIMER_TC_RC 3
Functions
static AT91S_TC * timer_base (uint8_t channel)
uint8_t timer_init (uint8_t channel)
uint8_t timer_prescaler_set (uint8_t channel, unsigned int period)
uint8_t timer_capture_mode_set (uint8_t channel)
uint8_t timer_capture_trigger_config (uint8_t channel, uint8_t ex_trg_edge, uint8_t ex_trg, uint8_t rc_comp_trg)
uint8_t timer_capture_register_load_config (uint8_t channel, uint8_t ldra, uint8_t ldrb, uint8_t ldrb_clk)
uint8_t timer_clock_enable (uint8_t channel)
uint16_t timer_read (uint8_t channel, uint8_t timer_reg)
uint8_t timer_reset (uint8_t channel)
uint8_t timer_disable (uint8_t channel)
Variables
static const uint8_t log_prescales [] = {1, 3, 5, 7, 10}
Detailed Description
Timer counter routines for AT91SAM7 processors.
Author:
Date: 12 February 2008
Define Documentation
#define EX_TRG_EACH 3
#define EX_TRG_FALLING 2
#define EX_TRG_NONE 0
#define EX_TRG_RISING 1
#define EX_TRG_TIOA 1
#define EX_TRG_TIOB 0
#define LDRA_TIOA_EACH 3
#define LDRA_TIOA_FALLING 2
#define LDRA_TIOA_NONE 0
#define LDRA_TIOA_RISING 1
#define LDRB_CLK_DIS 2
#define LDRB_CLK_NONE 0
#define LDRB_CLK_STOP 1
#define LDRB_CLK_STOP_DIS 3
#define LDRB_TIOA_EACH 3
#define LDRB_TIOA_FALLING 2
#define LDRB_TIOA_NONE 0
#define LDRB_TIOA_RISING 1
#define RC_COMP_NONE 0
#define RC_COMP_TRG 1
#define TIMER_CHANNEL_0 0
Referenced by timer_base(), and timer_init().
#define TIMER_CHANNEL_1 1
Referenced by timer_base(), and timer_init().
#define TIMER_CHANNEL_2 2
Referenced by timer_base(), and timer_init().
#define TIMER_TC_CV 0
Referenced by timer_read().
#define TIMER_TC_RA 1
Referenced by timer_read().
#define TIMER_TC_RB 2
Referenced by timer_read().
#define TIMER_TC_RC 3
Referenced by timer_read().
Function Documentation
static AT91S_TC* timer_base (uint8_t channel) [static]
References AT91C_BASE_TC0, AT91C_BASE_TC1, AT91C_BASE_TC2, TIMER_CHANNEL_0, TIMER_CHANNEL_1, and TIMER_CHANNEL_2.
Referenced by timer_capture_mode_set(), timer_capture_register_load_config(), timer_capture_trigger_config(), timer_clock_enable(), timer_disable(), timer_prescaler_set(), timer_read(), and timer_reset().
uint8_t timer_capture_mode_set (uint8_t channel)
References BITS_INSERT, and timer_base().
uint8_t timer_capture_register_load_config (uint8_t channel, uint8_t ldra, uint8_t ldrb, uint8_t ldrb_clk)
References BITS_EXTRACT, BITS_INSERT, and timer_base().
uint8_t timer_capture_trigger_config (uint8_t channel, uint8_t ex_trg_edge, uint8_t ex_trg, uint8_t rc_comp_trg)
References BITS_EXTRACT, BITS_INSERT, and timer_base().
uint8_t timer_clock_enable (uint8_t channel)
References AT91C_TC_CLKEN, and timer_base().
uint8_t timer_disable (uint8_t channel)
References AT91C_TC_CLKDIS, and timer_base().
uint8_t timer_init (uint8_t channel)
References AT91C_BASE_PMC, AT91C_ID_TC0, AT91C_ID_TC1, AT91C_ID_TC2, AT91C_PA0_TIOA0, AT91C_PA15_TIOA1, AT91C_PA16_TIOB1, AT91C_PA1_TIOB0, AT91C_PA26_TIOA2, AT91C_PA27_TIOB2, AT91C_PIOA_PDR, AT91C_PIOA_PPUDR, TIMER_CHANNEL_0, TIMER_CHANNEL_1, and TIMER_CHANNEL_2.
uint8_t timer_prescaler_set (uint8_t channel, unsigned int period)
References AT91C_TC_CLKS_TIMER_DIV1_CLOCK, AT91C_TC_CLKS_TIMER_DIV2_CLOCK, AT91C_TC_CLKS_TIMER_DIV3_CLOCK, AT91C_TC_CLKS_TIMER_DIV4_CLOCK, AT91C_TC_CLKS_TIMER_DIV5_CLOCK, BITS_INSERT, log_prescales, and timer_base().
uint16_t timer_read (uint8_t channel, uint8_t timer_reg)
References BITS_EXTRACT, timer_base(), TIMER_TC_CV, TIMER_TC_RA, TIMER_TC_RB, and TIMER_TC_RC.
uint8_t timer_reset (uint8_t channel)
References AT91C_TC_SWTRG, and timer_base().
Variable Documentation
const uint8_t log_prescales[] = {1, 3, 5, 7, 10} [static]
Referenced by timer_prescaler_set().