usb.c File Reference
#include `config.h`
#include `usb.h`
Data Structures
struct AT91S_CDC_LINE_CODING
Defines
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define AT91C_EP_OUT 1
#define AT91C_EP_OUT_SIZE 0x40
#define AT91C_EP_IN 2
#define AT91C_EP_IN_SIZE 0x40
#define STD_GET_STATUS_ZERO 0x0080
#define STD_GET_STATUS_INTERFACE 0x0081
#define STD_GET_STATUS_ENDPOINT 0x0082
#define STD_CLEAR_FEATURE_ZERO 0x0100
#define STD_CLEAR_FEATURE_INTERFACE 0x0101
#define STD_CLEAR_FEATURE_ENDPOINT 0x0102
#define STD_SET_FEATURE_ZERO 0x0300
#define STD_SET_FEATURE_INTERFACE 0x0301
#define STD_SET_FEATURE_ENDPOINT 0x0302
#define STD_SET_ADDRESS 0x0500
#define STD_GET_DESCRIPTOR 0x0680
#define STD_SET_DESCRIPTOR 0x0700
#define STD_GET_CONFIGURATION 0x0880
#define STD_SET_CONFIGURATION 0x0900
#define STD_GET_INTERFACE 0x0A81
#define STD_SET_INTERFACE 0x0B01
#define STD_SYNCH_FRAME 0x0C82
#define GET_LINE_CODING 0x21A1
#define SET_LINE_CODING 0x2021
#define SET_CONTROL_LINE_STATE 0x2221
Typedefs
typedef struct AT91S_CDC_LINE_CODING * AT91PS_CDC_LINE_CODING
Functions
static void usb_control_write (usb_t usb, const char *data, usb_size_t length)
void usb_control_write_zlp (usb_t usb)
void usb_control_stall (usb_t usb)
void usb_enumerate (usb_t usb)
usb_size_t usb_read (usb_t usb, char *data, usb_size_t length)
usb_size_t usb_write (usb_t usb, const char *data, usb_size_t length)
bool usb_configured_p (usb_t usb)
usb_t usb_init (void)
Variables
static const char devDescriptor []
static const char cfgDescriptor []
AT91S_CDC_LINE_CODING line
static usb_dev_t usb_dev
Define Documentation
#define AT91C_EP_IN 2
Referenced by usb_write().
#define AT91C_EP_IN_SIZE 0x40
Referenced by usb_write().
#define AT91C_EP_OUT 1
Referenced by usb_read().
#define AT91C_EP_OUT_SIZE 0x40
Referenced by usb_read().
#define GET_LINE_CODING 0x21A1
Referenced by usb_enumerate().
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
Referenced by usb_control_write(), usb_enumerate(), usb_read(), and usb_write().
#define SET_CONTROL_LINE_STATE 0x2221
Referenced by usb_enumerate().
#define SET_LINE_CODING 0x2021
Referenced by usb_enumerate().
#define STD_CLEAR_FEATURE_ENDPOINT 0x0102
Referenced by usb_enumerate().
#define STD_CLEAR_FEATURE_INTERFACE 0x0101
Referenced by usb_enumerate().
#define STD_CLEAR_FEATURE_ZERO 0x0100
Referenced by usb_enumerate().
#define STD_GET_CONFIGURATION 0x0880
Referenced by usb_enumerate().
#define STD_GET_DESCRIPTOR 0x0680
Referenced by usb_enumerate().
#define STD_GET_INTERFACE 0x0A81
#define STD_GET_STATUS_ENDPOINT 0x0082
Referenced by usb_enumerate().
#define STD_GET_STATUS_INTERFACE 0x0081
Referenced by usb_enumerate().
#define STD_GET_STATUS_ZERO 0x0080
Referenced by usb_enumerate().
#define STD_SET_ADDRESS 0x0500
Referenced by usb_enumerate().
#define STD_SET_CONFIGURATION 0x0900
Referenced by usb_enumerate().
#define STD_SET_DESCRIPTOR 0x0700
#define STD_SET_FEATURE_ENDPOINT 0x0302
Referenced by usb_enumerate().
#define STD_SET_FEATURE_INTERFACE 0x0301
Referenced by usb_enumerate().
#define STD_SET_FEATURE_ZERO 0x0300
Referenced by usb_enumerate().
#define STD_SET_INTERFACE 0x0B01
#define STD_SYNCH_FRAME 0x0C82
Typedef Documentation
typedef struct AT91S_CDC_LINE_CODING * AT91PS_CDC_LINE_CODING
Function Documentation
bool usb_configured_p (usb_t usb)
References AT91C_UDP_ENDBUSRES, AT91C_UDP_EPEDS, AT91C_UDP_EPINT0, AT91C_UDP_EPTYPE_CTRL, AT91C_UDP_FEN, usb_struct::currentConfiguration, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FADDR, _AT91S_UDP::UDP_ICR, _AT91S_UDP::UDP_ISR, _AT91S_UDP::UDP_RSTEP, and usb_enumerate().
Referenced by usb_read(), and usb_write().
void usb_control_stall (usb_t usb)
References AT91C_UDP_FORCESTALL, AT91C_UDP_ISOERROR, usb_struct::pUDP, and _AT91S_UDP::UDP_CSR.
Referenced by usb_enumerate().
static void usb_control_write (usb_t usb, const char * data, usb_size_t length) [static]
References AT91C_UDP_RX_DATA_BK0, AT91C_UDP_TXCOMP, AT91C_UDP_TXPKTRDY, MIN, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, and _AT91S_UDP::UDP_FDR.
Referenced by usb_enumerate().
void usb_control_write_zlp (usb_t usb)
References AT91C_UDP_TXCOMP, AT91C_UDP_TXPKTRDY, usb_struct::pUDP, and _AT91S_UDP::UDP_CSR.
Referenced by usb_enumerate().
void usb_enumerate (usb_t usb)
References AT91C_UDP_CONFG, AT91C_UDP_DIR, AT91C_UDP_EPEDS, AT91C_UDP_EPTYPE_BULK_IN, AT91C_UDP_EPTYPE_BULK_OUT, AT91C_UDP_EPTYPE_ISO_IN, AT91C_UDP_FADDEN, AT91C_UDP_FEN, AT91C_UDP_RX_DATA_BK0, AT91C_UDP_RXSETUP, cfgDescriptor, usb_struct::currentConfiguration, usb_struct::currentConnection, devDescriptor, GET_LINE_CODING, MIN, usb_struct::pUDP, SET_CONTROL_LINE_STATE, SET_LINE_CODING, STD_CLEAR_FEATURE_ENDPOINT, STD_CLEAR_FEATURE_INTERFACE, STD_CLEAR_FEATURE_ZERO, STD_GET_CONFIGURATION, STD_GET_DESCRIPTOR, STD_GET_STATUS_ENDPOINT, STD_GET_STATUS_INTERFACE, STD_GET_STATUS_ZERO, STD_SET_ADDRESS, STD_SET_CONFIGURATION, STD_SET_FEATURE_ENDPOINT, STD_SET_FEATURE_INTERFACE, STD_SET_FEATURE_ZERO, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FADDR, _AT91S_UDP::UDP_FDR, _AT91S_UDP::UDP_GLBSTATE, usb_control_stall(), usb_control_write(), and usb_control_write_zlp().
Referenced by usb_configured_p().
usb_t usb_init (void)
References AT91C_BASE_CKGR, AT91C_BASE_PIOA, AT91C_BASE_PMC, AT91C_BASE_UDP, AT91C_CKGR_USBDIV_1, AT91C_ID_UDP, AT91C_PIO_PA16, AT91C_PMC_UDP, AT91C_UDP_RX_DATA_BK0, AT91F_PIO_CfgOutput(), AT91F_PIO_ClearOutput(), usb_struct::currentConfiguration, usb_struct::currentConnection, usb_struct::currentRcvBank, and usb_struct::pUDP.
usb_size_t usb_read (usb_t usb, char * data, usb_size_t length)
References AT91C_EP_OUT, AT91C_EP_OUT_SIZE, AT91C_UDP_RX_DATA_BK0, AT91C_UDP_RX_DATA_BK1, usb_struct::currentRcvBank, MIN, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FDR, and usb_configured_p().
usb_size_t usb_write (usb_t usb, const char * data, usb_size_t length)
References AT91C_EP_IN, AT91C_EP_IN_SIZE, AT91C_UDP_TXCOMP, AT91C_UDP_TXPKTRDY, MIN, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FDR, and usb_configured_p().
Variable Documentation
const char cfgDescriptor[] [static]
Referenced by usb_enumerate().
const char devDescriptor[] [static]
Initial value:
{
    
    0x12,   
    0x01,   
    0x10,   
    0x01,   
    0x02,   
    0x00,   
    0x00,   
    0x08,   
    0xEB,   
    0x03,   
    0x24,   
    0x61,   
    0x10,   
    0x01,   
    0x00,   
    0x00,   
    0x00,   
    0x01    
}
Referenced by usb_enumerate().
AT91S_CDC_LINE_CODING line
Initial value:
{
    115200, 
    0,      
    0,      
    8
}
usb_dev_t usb_dev [static]