usb.h File Reference
#include `config.h`
Data Structures
struct usb_struct
Typedefs
typedef struct usb_struct usb_dev_t
typedef usb_dev_t * usb_t
typedef uint16_t usb_size_t
Functions
usb_size_t usb_write (usb_t usb, const char *data, usb_size_t length)
usb_size_t usb_read (usb_t usb, char *data, usb_size_t length)
bool usb_configured_p (usb_t dev)
usb_t usb_init (void)
Typedef Documentation
typedef struct usb_struct usb_dev_t
typedef uint16_t usb_size_t
typedef usb_dev_t* usb_t
Function Documentation
bool usb_configured_p (usb_t dev)
References AT91C_UDP_ENDBUSRES, AT91C_UDP_EPEDS, AT91C_UDP_EPINT0, AT91C_UDP_EPTYPE_CTRL, AT91C_UDP_FEN, usb_struct::currentConfiguration, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FADDR, _AT91S_UDP::UDP_ICR, _AT91S_UDP::UDP_ISR, _AT91S_UDP::UDP_RSTEP, and usb_enumerate().
Referenced by usb_read(), and usb_write().
usb_t usb_init (void)
References AT91C_BASE_CKGR, AT91C_BASE_PIOA, AT91C_BASE_PMC, AT91C_BASE_UDP, AT91C_CKGR_USBDIV_1, AT91C_ID_UDP, AT91C_PIO_PA16, AT91C_PMC_UDP, AT91C_UDP_RX_DATA_BK0, AT91F_PIO_CfgOutput(), AT91F_PIO_ClearOutput(), usb_struct::currentConfiguration, usb_struct::currentConnection, usb_struct::currentRcvBank, and usb_struct::pUDP.
usb_size_t usb_read (usb_t usb, char * data, usb_size_t length)
References AT91C_EP_OUT, AT91C_EP_OUT_SIZE, AT91C_UDP_RX_DATA_BK0, AT91C_UDP_RX_DATA_BK1, usb_struct::currentRcvBank, MIN, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FDR, and usb_configured_p().
usb_size_t usb_write (usb_t usb, const char * data, usb_size_t length)
References AT91C_EP_IN, AT91C_EP_IN_SIZE, AT91C_UDP_TXCOMP, AT91C_UDP_TXPKTRDY, MIN, usb_struct::pUDP, _AT91S_UDP::UDP_CSR, _AT91S_UDP::UDP_FDR, and usb_configured_p().