ads7870.h File Reference
ADS7870 SPI ADC.
#include `config.h`
Functions
void ads7870_init (void)
int16_t ads7870_read (void)
int16_t ads7870_convert (void)
void ads7870_channel_start (uint8_t channel, spi_adc_mode_t mode)
int16_t ads7870_channel_convert (uint8_t channel, spi_adc_mode_t mode)
Detailed Description
ADS7870 SPI ADC.
Author: M. P. Hayes, UCECE
Date: 09 August 2007
Function Documentation
int16_t ads7870_channel_convert (uint8_t channel, spi_adc_mode_t mode)
References ads7870_channel_start(), ads7870_read(), and ads7870_read_ready_p().
void ads7870_channel_start (uint8_t channel, spi_adc_mode_t mode)
References ads7870_chip_select(), ADS7870_CONVERT, SPI_ADC_MODE_DIFFERENTIAL, SPI_ADC_MODE_DIFFERENTIAL_INVERTED, and SPI_ADC_MODE_SINGLE_ENDED.
Referenced by ads7870_channel_convert().
int16_t ads7870_convert (void)
void ads7870_init (void)
References ADS7870_REFOSC, ADS7870_REFOSC_BUFE, ADS7870_REFOSC_OSCE, ADS7870_REFOSC_REFE, and ads7870_reg_write().
int16_t ads7870_read (void)
References ads7870_chip_deselect(), ads7870_chip_select(), ADS7870_REG_16BIT, ADS7870_REG_READ, and ADS7870_RESULTHI.
Referenced by ads7870_channel_convert().