ads8327.c File Reference
#include `config.h`
#include `port.h`
#include `spi.h`
#include `spi_adc.h`
Functions
static void ads8327_chip_select (void)
static void ads8327_chip_deselect (void)
static uint16_t ads8327_command (uint16_t val)
void ads8327_init (void)
int16_t ads8327_read (void)
int16_t ads8327_convert (void)
Function Documentation
static void ads8327_chip_deselect (void) [static]
Referenced by ads8327_command(), and ads8327_read().
static void ads8327_chip_select (void) [static]
Referenced by ads8327_command(), and ads8327_read().
static uint16_t ads8327_command (uint16_t val) [static]
References ads8327_chip_deselect(), and ads8327_chip_select().
Referenced by ads8327_init().
int16_t ads8327_convert (void)
References ads8327_read().
void ads8327_init (void)
References ads8327_command().
int16_t ads8327_read (void)
References ads8327_chip_deselect(), and ads8327_chip_select().
Referenced by ads8327_convert().