ads8327.h File Reference
ADS8327 SPI ADC.
#include `config.h`
Functions
void ads8327_init (void)
int16_t ads8327_convert (void)
int16_t ads8327_read (void)
Detailed Description
ADS8327 SPI ADC.
Author: M. P. Hayes, UCECE
Date: 09 August 2007
Function Documentation
int16_t ads8327_convert (void)
References ads8327_read().
void ads8327_init (void)
References ads8327_command().
int16_t ads8327_read (void)
References ads8327_chip_deselect(), and ads8327_chip_select().
Referenced by ads8327_convert().