busart.c File Reference
Buffered USART implementation.
#include `ring.h`
#include `busart.h`
#include `peripherals.h`
#include <string.h>
Data Structures
struct busart_dev_struct
Defines
#define BUSART0_ENABLE (USART_NUM >= 1)
#define BUSART1_ENABLE (USART_NUM >= 2)
Functions
busart_t busart_init (uint8_t channel, uint16_t baud_divisor, char *tx_buffer, ring_size_t tx_size, char *rx_buffer, ring_size_t rx_size)
ring_size_t busart_write (busart_t busart, const void *data, ring_size_t size)
ring_size_t busart_write_block (busart_t busart, const void *data, ring_size_t size)
ring_size_t busart_read (busart_t busart, void *data, ring_size_t size)
ring_size_t busart_read_block (busart_t busart, void *data, ring_size_t size)
ring_size_t busart_read_num (busart_t busart)
ring_size_t busart_write_num (busart_t busart)
bool busart_read_ready_p (busart_t busart)
bool busart_write_ready_p (busart_t busart)
bool busart_write_finished_p (busart_t busart)
int8_t busart_getc (busart_t busart)
int8_t busart_putc (busart_t busart, char ch)
int8_t busart_puts (busart_t busart, const char *str)
Detailed Description
Buffered USART implementation.
Author: M. P. Hayes, UCECE
Date: 15 May 2007
Define Documentation
#define BUSART0_ENABLE (USART_NUM >= 1)
A BUSART can be disabled in the target.h file, e.g., using define BUSART0_ENABLE 0.
#define BUSART1_ENABLE (USART_NUM >= 2)
Function Documentation
int8_t busart_getc (busart_t busart)
Read character. This blocks until the character can be read.
References busart_read_block().
busart_t busart_init (uint8_t channel, uint16_t baud_divisor, char * tx_buffer, ring_size_t tx_size, char * rx_buffer, ring_size_t rx_size)
References ring_init(), busart_dev_struct::rx_irq_enable, busart_dev_struct::rx_ring, and busart_dev_struct::tx_ring.
int8_t busart_putc (busart_t busart, char ch)
Write character. This blocks until the character can be written.
References busart_putc(), and busart_write_block().
Referenced by busart_putc(), and busart_puts().
int8_t busart_puts (busart_t busart, const char * str)
Write string. This blocks until the string is buffered.
References busart_putc().
ring_size_t busart_read (busart_t busart, void * data, ring_size_t size)
Read as many bytes as there are available in the ring buffer up to the specifed size.
References ring_read(), and busart_dev_struct::rx_ring.
Referenced by busart_read_block().
ring_size_t busart_read_block (busart_t busart, void * data, ring_size_t size)
Read size bytes. This will block until the desired number of bytes have been read.
References busart_read().
Referenced by busart_getc().
ring_size_t busart_read_num (busart_t busart)
Return the number of bytes immediately available for reading.
References ring_read_num(), and busart_dev_struct::rx_ring.
Referenced by busart_read_ready_p().
bool busart_read_ready_p (busart_t busart)
Return non-zero if there is a character ready to be read.
References busart_read_num().
ring_size_t busart_write (busart_t busart, const void * data, ring_size_t size)
Write size bytes. Currently this only writes as many bytes (up to the desired size) that can currently fit in the ring buffer.
References ring_write(), busart_dev_struct::tx_irq_enable, and busart_dev_struct::tx_ring.
Referenced by busart_write_block().
ring_size_t busart_write_block (busart_t busart, const void * data, ring_size_t size)
Write size bytes. This will block until the desired number of bytes have been written.
References busart_write().
Referenced by busart_putc().
bool busart_write_finished_p (busart_t busart)
Return non-zero if transmitter finished.
References ring_empty_p(), busart_dev_struct::tx_finished_p, and busart_dev_struct::tx_ring.
ring_size_t busart_write_num (busart_t busart)
Return the number of bytes immediately available for writing.
References ring_write_num(), and busart_dev_struct::tx_ring.
Referenced by busart_write_ready_p().
bool busart_write_ready_p (busart_t busart)
Return non-zero if a character can be written without blocking.
References busart_write_num().