button.h File Reference
Button polling and debouncing.
#include `config.h`
#include `port.h`
Data Structures
struct button_cfg_t
struct button_private_t
Defines
#define BUTTON_DEBOUNCE_RATE (1000 / BUTTON_DEBOUNCE_MS)
#define BUTTON_POLL_COUNT(POLL_RATE) ((POLL_RATE) / BUTTON_DEBOUNCE_RATE)
#define BUTTON_CFG(PORT, PORTBIT) {(PORT), BIT (PORTBIT)}
Typedefs
typedef button_private_t button_obj_t
typedef button_obj_t * button_t
Enumerations
enum { BUTTON_DEBOUNCE_MS = 50
 }
enum button_state_t { BUTTON_STATE_UP,
BUTTON_STATE_DOWN,
BUTTON_STATE_PUSHED,
BUTTON_STATE_RELEASED
 }
Functions
void button_poll_count_set (uint8_t poll_count)
button_t button_init (button_obj_t *obj, const button_cfg_t *cfg)
button_state_t button_poll (button_t button)
static button_state_t button_state_get (button_t button)
static uint8_t button_hold_count_get (button_t button)
static bool button_pushed_p (button_t button)
static bool button_released_p (button_t button)
static bool button_down_p (button_t button)
static bool button_up_p (button_t button)
static bool button_held_p (button_t button, uint8_t hold_count)
static bool button_hold_released_p (button_t button, uint8_t hold_count)
static bool button_pressed_p (button_t button)
Detailed Description
Button polling and debouncing.
Author: M. P. Hayes, UCECE
Date: 15 Feb 2003
Define Documentation
#define BUTTON_CFG(PORT, PORTBIT) {(PORT), BIT (PORTBIT)}
#define BUTTON_DEBOUNCE_RATE (1000 / BUTTON_DEBOUNCE_MS)
#define BUTTON_POLL_COUNT(POLL_RATE) ((POLL_RATE) / BUTTON_DEBOUNCE_RATE)
Typedef Documentation
typedef button_private_t button_obj_t
typedef button_obj_t* button_t
Enumeration Type Documentation
anonymous enum
Debounce period in milliseconds.
Enumerator:
BUTTON_DEBOUNCE_MS
enum button_state_t
Button states.
Enumerator:
BUTTON_STATE_UP
BUTTON_STATE_DOWN
BUTTON_STATE_PUSHED
BUTTON_STATE_RELEASED
Function Documentation
static bool button_down_p (button_t button) [static]
Return true if button down (pressed).
Parameters:
button pointer to button object
Returns: 1 if button down otherwise 0
References BUTTON_STATE_DOWN, and button_state_get().
Referenced by button_held_p().
static bool button_held_p (button_t button, uint8_t hold_count) [static]
Return true if button held for hold_count.
Parameters:
button pointer to button object
hold_count hold duration (in update periods)
Returns: 1 if button held for specified count otherwise 0
References button_down_p(), and button_hold_count_get().
Referenced by buttons_held_p(), and mbuttons_held_p().
static uint8_t button_hold_count_get (button_t button) [static]
Return duration button held (in update periods).
Parameters:
button pointer to button object
Returns: duration button held
References button_private_t::hold_count.
Referenced by button_held_p(), and button_hold_released_p().
static bool button_hold_released_p (button_t button, uint8_t hold_count) [static]
Return true if button held for hold_count has been released.
Parameters:
button pointer to button object
hold_count hold duration (in update periods)
Returns: 1 if button held for specified count is now released otherwise 0
References button_hold_count_get(), and button_released_p().
Referenced by buttons_hold_released_p(), and mbuttons_hold_released_p().
button_t button_init (button_obj_t * obj, const button_cfg_t * cfg)
Create a new button object.
Parameters:
obj pointer to button structure
cfg pointer to button configuration
Returns: pointer to button object
References button_cfg_t::bitmask, BUTTON_STATE_UP, button_private_t::cfg, button_private_t::count, button_private_t::hold_count, button_cfg_t::port, and button_private_t::state.
Referenced by buttons_init(), and mbuttons_init().
button_state_t button_poll (button_t button)
Poll the specified button and return its debounced state.
Parameters:
button pointer to button object
Returns: button state
Poll the specified button and return its debounced state.
Parameters:
button pointer to button object
Returns: button state
References button_debounce(), and button_pressed_p().
Referenced by buttons_poll(), and mbuttons_poll().
void button_poll_count_set (uint8_t poll_count)
Set the number of polls required for the debounce period.
Parameters:
poll_count number of update periods
References button_poll_count.
Referenced by buttons_init(), and mbuttons_init().
static bool button_pressed_p (button_t button) [static]
Return true if button possibly pressed.
Parameters:
button pointer to button object
Returns: 1 if button currently pressed otherwise 0
Note: This is not debounced. For a debounced version use button_pushed_p.
References button_cfg_t::bitmask, button_private_t::cfg, and button_cfg_t::port.
Referenced by button_poll(), and mbuttons_wakeup_p().
static bool button_pushed_p (button_t button) [static]
Return true if button pushed.
Parameters:
button pointer to button object
Returns: 1 if button pushed otherwise 0
References button_state_get(), and BUTTON_STATE_PUSHED.
Referenced by buttons_any_pushed_p(), buttons_pushed_p(), and mbuttons_pushed_p().
static bool button_released_p (button_t button) [static]
Return true if button released.
Parameters:
button pointer to button object
Returns: 1 if button released otherwise 0
References button_state_get(), and BUTTON_STATE_RELEASED.
Referenced by button_hold_released_p(), buttons_released_p(), and mbuttons_released_p().
static button_state_t button_state_get (button_t button) [static]
Return button state.
Parameters:
button pointer to button object
Returns: button state
References button_private_t::state.
Referenced by button_down_p(), button_pushed_p(), button_released_p(), button_up_p(), and mbuttons_any_state_p().
static bool button_up_p (button_t button) [static]
Return true if button up.
Parameters:
button pointer to button object
Returns: 1 if button down otherwise 0
References button_state_get(), and BUTTON_STATE_UP.