buttons.h File Reference
Multiple button polling and debouncing.
#include `button.h`
Data Structures
struct buttons_private_t
Typedefs
typedef buttons_private_t buttons_obj_t
typedef buttons_obj_t * buttons_t
Functions
void buttons_init (buttons_obj_t *buttons, button_obj_t *buttons_info, const button_cfg_t *config, uint8_t buttons_num, uint8_t poll_count)
void buttons_poll (buttons_t buttons)
bool buttons_any_pushed_p (buttons_t buttons)
static bool buttons_pushed_p (buttons_t buttons, uint8_t id)
static bool buttons_released_p (buttons_t buttons, uint8_t id)
static bool buttons_held_p (buttons_t buttons, uint8_t id, uint8_t hold_count)
static bool buttons_hold_released_p (buttons_t buttons, uint8_t id, uint8_t hold_count)
Detailed Description
Multiple button polling and debouncing.
Author: M. P. Hayes, UCECE
Date: 17 Nov 2006
Typedef Documentation
typedef buttons_private_t buttons_obj_t
typedef buttons_obj_t* buttons_t
Function Documentation
bool buttons_any_pushed_p (buttons_t buttons)
Return true if any buttons pushed.
References button_pushed_p(), buttons_private_t::buttons, and buttons_private_t::num.
static bool buttons_held_p (buttons_t buttons, uint8_t id, uint8_t hold_count) [static]
Return true if selected button held for hold_count.
References button_held_p(), and buttons_private_t::buttons.
static bool buttons_hold_released_p (buttons_t buttons, uint8_t id, uint8_t hold_count) [static]
Return true if selected button held for hold_count is released.
References button_hold_released_p(), and buttons_private_t::buttons.
void buttons_init (buttons_obj_t * buttons, button_obj_t * buttons_info, const button_cfg_t * config, uint8_t buttons_num, uint8_t poll_count)
Initialise multiple buttons.
References button_init(), button_poll_count_set(), buttons_private_t::buttons, and buttons_private_t::num.
void buttons_poll (buttons_t buttons)
Poll multiple buttons.
References button_poll(), buttons_private_t::buttons, and buttons_private_t::num.
static bool buttons_pushed_p (buttons_t buttons, uint8_t id) [static]
Return true if selected button pushed.
References button_pushed_p(), and buttons_private_t::buttons.
static bool buttons_released_p (buttons_t buttons, uint8_t id) [static]
Return true if selected button released.
References button_released_p(), and buttons_private_t::buttons.