button.c File Reference
Button polling and debouncing.
#include `button.h`
Functions
void button_poll_count_set (uint8_t poll_count)
button_t button_init (button_obj_t *obj, const button_cfg_t *cfg)
static button_state_t button_debounce (button_t button, bool pressed)
button_state_t button_poll (button_t button)
Variables
static uint8_t button_poll_count
Detailed Description
Button polling and debouncing.
Author: M.P. Hayes
Date: 16 Feb 2003
Note: This debounces pushbuttons and switches using a polled wait-and-see method implemented with a state machine. It assumes that a pushed button gives a logic low on the input port.
Function Documentation
static button_state_t button_debounce (button_t button, bool pressed) [static]
Debounce specified button and return its debounced state.
Parameters:
button pointer to button object
pressed true if button current pressed
Returns: button state
References button_poll_count, BUTTON_STATE_DOWN, BUTTON_STATE_PUSHED, BUTTON_STATE_RELEASED, BUTTON_STATE_UP, button_private_t::count, button_private_t::hold_count, and button_private_t::state.
Referenced by button_poll().
button_t button_init (button_obj_t * obj, const button_cfg_t * cfg)
Create a new button object.
Parameters:
obj pointer to button structure
cfg pointer to button configuration
Returns: pointer to button object
References button_cfg_t::bitmask, BUTTON_STATE_UP, button_private_t::cfg, button_private_t::count, button_private_t::hold_count, button_cfg_t::port, and button_private_t::state.
Referenced by buttons_init(), and mbuttons_init().
button_state_t button_poll (button_t button)
Poll the specified button and return its debounced state.
Parameters:
button pointer to button object
Returns: button state
References button_debounce(), and button_pressed_p().
Referenced by buttons_poll(), and mbuttons_poll().
void button_poll_count_set (uint8_t poll_count)
Set the number of polls required for the debounce period.
Parameters:
poll_count number of update periods
References button_poll_count.
Referenced by buttons_init(), and mbuttons_init().
Variable Documentation
uint8_t button_poll_count [static]
Referenced by button_debounce(), and button_poll_count_set().