chaser.c File Reference
#include <limits.h>
#include `chaser.h`
#include `flasher.h`
#include `font.h`
Functions
chaser_t chaser_init (chaser_obj_t *dev, flasher_t *flashers, uint8_t flasher_num)
void chaser_sequence_set (chaser_t chaser, chaser_sequence_t seq)
void chaser_mode_set (chaser_t chaser, chaser_mode_t mode)
static void chaser_pixel_set (void *data, font_t *font, uint8_t col, uint8_t row, bool val)
int8_t chaser_update (chaser_t chaser)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 15 May 2007
Function Documentation
chaser_t chaser_init (chaser_obj_t * dev, flasher_t * flashers, uint8_t flasher_num)
References CHASER_MODE_NORMAL, chaser_private_t::dir, chaser_private_t::flasher_num, chaser_private_t::flashers, chaser_private_t::mode, and chaser_private_t::step.
void chaser_mode_set (chaser_t chaser, chaser_mode_t mode)
References chaser_private_t::dir, chaser_private_t::mode, and chaser_private_t::step.
static void chaser_pixel_set (void * data, font_t * font, uint8_t col, uint8_t row, bool val) [static]
References CHASER_MODE_CYCLE_INVERT, CHASER_MODE_INVERT, flasher_pattern_set(), chaser_private_t::flashers, chaser_private_t::mode, chaser_private_t::off_pattern, chaser_private_t::on_pattern, and font_t::width.
Referenced by chaser_update().
void chaser_sequence_set (chaser_t chaser, chaser_sequence_t seq)
References chaser_private_t::dir, chaser_private_t::seq, and chaser_private_t::step.
int8_t chaser_update (chaser_t chaser)
References CHASER_MODE_CYCLE, CHASER_MODE_CYCLE_INVERT, chaser_pixel_set(), chaser_private_t::dir, chaser_private_t::font, font_display(), chaser_private_t::mode, chaser_private_t::seq, and chaser_private_t::step.