cleds.h File Reference
#include `config.h`
#include `port.h`
#include `led.h`
Data Structures
struct cleds_private_t
Typedefs
typedef cleds_private_t cleds_obj_t
typedef cleds_obj_t * cleds_t
Functions
void cleds_init (cleds_obj_t *cleds, const led_cfg_t *row_config, uint8_t rows_num, const led_cfg_t *col_config, uint8_t cols_num)
uint8_t cleds_common_set (cleds_t cleds, uint8_t row)
static void cleds_set (cleds_t cleds, uint8_t id, uint8_t val)
static uint8_t cleds_cols_num_get (cleds_t cleds)
static uint8_t cleds_rows_num_get (cleds_t cleds)
static uint8_t cleds_active_row_get (cleds_t cleds)
static uint8_t cleds_common_cycle (cleds_t cleds)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 29 June 2007
Typedef Documentation
typedef cleds_private_t cleds_obj_t
typedef cleds_obj_t* cleds_t
Function Documentation
static uint8_t cleds_active_row_get (cleds_t cleds) [static]
References cleds_private_t::row.
static uint8_t cleds_cols_num_get (cleds_t cleds) [static]
References cleds_private_t::cols_num.
Referenced by mcleds_enable(), mcleds_off(), and mcleds_update().
static uint8_t cleds_common_cycle (cleds_t cleds) [static]
References cleds_common_set(), cleds_private_t::row, and cleds_private_t::rows_num.
uint8_t cleds_common_set (cleds_t cleds, uint8_t row)
References cleds_private_t::row, and cleds_private_t::row_config.
Referenced by cleds_common_cycle(), mcleds_disable(), mcleds_enable(), mcleds_init(), and mcleds_update().
void cleds_init (cleds_obj_t * cleds, const led_cfg_t * row_config, uint8_t rows_num, const led_cfg_t * col_config, uint8_t cols_num)
References cleds_private_t::cols_num, led_init(), cleds_private_t::leds, cleds_private_t::row, cleds_private_t::row_config, and cleds_private_t::rows_num.
Referenced by mcleds_init().
static uint8_t cleds_rows_num_get (cleds_t cleds) [static]
References cleds_private_t::rows_num.
Referenced by mcleds_update().
static void cleds_set (cleds_t cleds, uint8_t id, uint8_t val) [static]
References led_set(), and cleds_private_t::leds.
Referenced by mcleds_enable(), mcleds_off(), and mcleds_update().