cleds.c File Reference
#include `cleds.h`
#include `port.h`
Functions
void cleds_init (cleds_obj_t *cleds, const led_cfg_t *row_config, uint8_t rows_num, const led_cfg_t *col_config, uint8_t cols_num)
uint8_t cleds_common_set (cleds_t cleds, uint8_t row)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 29 June 2007
Function Documentation
uint8_t cleds_common_set (cleds_t cleds, uint8_t row)
References cleds_private_t::row, and cleds_private_t::row_config.
Referenced by cleds_common_cycle(), mcleds_disable(), mcleds_enable(), mcleds_init(), and mcleds_update().
void cleds_init (cleds_obj_t * cleds, const led_cfg_t * row_config, uint8_t rows_num, const led_cfg_t * col_config, uint8_t cols_num)
References cleds_private_t::cols_num, led_init(), cleds_private_t::leds, cleds_private_t::row, cleds_private_t::row_config, and cleds_private_t::rows_num.
Referenced by mcleds_init().