dscrc8.c File Reference
8-bit CRC routines for Dallas Semiconductor one wire bus.
#include `dscrc8.h`
Functions
crc8_t dscrc8_byte (crc8_t crc, uint8_t val)
crc8_t dscrc8 (crc8_t crc, uint8_t *bytes, uint8_t size)
Detailed Description
8-bit CRC routines for Dallas Semiconductor one wire bus.
Author: M. P. Hayes, UCECE
Date: 15 May 2007
Function Documentation
crc8_t dscrc8 (crc8_t crc, uint8_t * bytes, uint8_t size)
Update CRC for a number of bytes.
Parameters:
crc CRC value
bytes pointer to array of bytes
size number of bytes to process
Returns: new CRC
References dscrc8_byte().
Referenced by ds18b20_temp_read().
crc8_t dscrc8_byte (crc8_t crc, uint8_t val)
Update CRC for a single byte.
Parameters:
crc CRC value
val value to update CRC with
Returns: new CRC
Referenced by dscrc8(), and u1wire_search().