dscrc16.c File Reference
#include `dscrc16.h`
Functions
static crc16_t dscrc16_bit (crc16_t crc, uint8_t in)
crc16_t dscrc16_byte (crc16_t crc, uint8_t val)
crc16_t dscrc16 (crc16_t crc, void *bytes, uint8_t size)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 15 May 2007
Function Documentation
crc16_t dscrc16 (crc16_t crc, void * bytes, uint8_t size)
References dscrc16_byte().
Referenced by ds2450_memory_read().
static crc16_t dscrc16_bit (crc16_t crc, uint8_t in) [static]
Referenced by dscrc16_byte().
crc16_t dscrc16_byte (crc16_t crc, uint8_t val)
References dscrc16_bit().
Referenced by ds2450_adc_conversion_start(), ds2450_memory_read(), and dscrc16().