flasher.c File Reference
#include `flasher.h`
Defines
#define FLASHER_TRANSPARENT
Functions
int8_t flasher_pattern_set (flasher_t flasher, flasher_pattern_t *pattern)
flasher_pattern_t * flasher_pattern_get (flasher_t flasher)
int8_t flasher_phase_set (flasher_t flasher, uint8_t phase)
bool flasher_update (flasher_t flasher)
flasher_t flasher_init (flasher_obj_t *flasher)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 13 March 2005
Define Documentation
#define FLASHER_TRANSPARENT
Function Documentation
flasher_t flasher_init (flasher_obj_t * flasher)
References flasher_pattern_set().
flasher_pattern_t* flasher_pattern_get (flasher_t flasher)
int8_t flasher_pattern_set (flasher_t flasher, flasher_pattern_t * pattern)
Referenced by chaser_pixel_set(), and flasher_init().
int8_t flasher_phase_set (flasher_t flasher, uint8_t phase)
bool flasher_update (flasher_t flasher)
References FLASHER_PRESCALE.