font.h File Reference
Font support.
#include `config.h`
Data Structures
struct font_t
Typedefs
typedef const uint8_t font_elt_t
typedef void(* font_callback_t)(void *data, font_t *font, uint8_t col, uint8_t row, bool val)
Functions
bool font_display (char ch, font_t *font, font_callback_t display, void *data)
Detailed Description
Font support.
Author: M. P. Hayes, UCECE
Date: 1 March 2007
Typedef Documentation
typedef void(* font_callback_t)(void *data, font_t *font, uint8_t col, uint8_t row, bool val)
typedef const uint8_t font_elt_t
Function Documentation
bool font_display (char ch, font_t * font, font_callback_t display, void * data)
Call callback function for every pixel in font.
Parameters:
ch character to display
font point to font structure
display pointer to callback function
data pointer to pass to callback function
Returns: 1 if ch in font otherwise 0
Call callback function for every pixel in font.
Parameters:
ch character to display
font point to font structure
display pointer to callback function
data pointer to pass to callback function
Returns: 1 if ch in font otherwise 0
References font_t::data, font_t::height, font_t::offset, font_t::size, and font_t::width.
Referenced by chaser_update(), glcd_text(), mtext_display(), and stext_display().