font.c File Reference
Font support.
#include `font.h`
Functions
bool font_display (char ch, font_t *font, font_callback_t display, void *data)
Detailed Description
Font support.
Author: M. P. Hayes, UCECE
Date: 1 March 2007
Function Documentation
bool font_display (char ch, font_t * font, font_callback_t display, void * data)
Call callback function for every pixel in font.
Parameters:
ch character to display
font point to font structure
display pointer to callback function
data pointer to pass to callback function
Returns: 1 if ch in font otherwise 0
References font_t::data, font_t::height, font_t::offset, font_t::size, and font_t::width.
Referenced by chaser_update(), glcd_text(), mtext_display(), and stext_display().