glcd_text.c File Reference
#include `glcd.h`
#include `font.h`
Data Structures
struct glcd_text_t
Functions
static void display_pixel (glcd_text_t *info, font_t *font __UNUSED__, uint8_t col, uint8_t row, bool val)
void glcd_text (glcd_t glcd, font_t *font, uint8_t col, uint8_t row, const char *str)
Function Documentation
static void display_pixel (glcd_text_t * info, font_t *font __UNUSED__, uint8_t col, uint8_t row, bool val) [static]
References glcd_text_t::col, glcd_text_t::glcd, glcd_pixel_set(), and glcd_text_t::row.
Referenced by glcd_text().
void glcd_text (glcd_t glcd, font_t * font, uint8_t col, uint8_t row, const char * str)
References glcd_text_t::col, display_pixel(), font_display(), glcd_text_t::glcd, glcd_update(), font_t::height, glcd_text_t::row, and font_t::width.
Referenced by textview_putc_1(), and textview_redraw().