glcd.h File Reference
Simple GLCD driver.
#include `config.h`
#include `port.h`
#include `spi.h`
Data Structures
struct glcd_cfg_t
struct glcd_private_t
Defines
#define GLCD_WIDTH 128
#define GLCD_HEIGHT 64
#define GLCD_PIXEL_BITS 1
#define GLCD_CFG(PORT, PORTBIT) {(PORT), BIT (PORTBIT)}
#define GLCD_PAGE_PIXELS 8
#define GLCD_PAGES (GLCD_HEIGHT / GLCD_PAGE_PIXELS)
#define GLCD_PIXEL_BYTES (GLCD_PAGES * GLCD_WIDTH * GLCD_PIXEL_BITS)
Typedefs
typedef glcd_private_t glcd_obj_t
typedef glcd_obj_t * glcd_t
Functions
void glcd_pixel_set (glcd_t glcd, uint16_t x, uint16_t y, uint8_t val)
void glcd_update (glcd_t glcd)
void glcd_clear (glcd_t glcd)
void glcd_contrast_set (glcd_t glcd, uint8_t contrast)
glcd_t glcd_init (glcd_obj_t *obj, const glcd_cfg_t *cfg)
void glcd_shutdown (glcd_obj_t *obj)
Detailed Description
Simple GLCD driver.
Author: M. P. Hayes, UCECE
Date: 28 January 2008
Define Documentation
#define GLCD_CFG(PORT, PORTBIT) {(PORT), BIT (PORTBIT)}
#define GLCD_HEIGHT 64
Referenced by glcd_pixel_set().
#define GLCD_PAGE_PIXELS 8
Referenced by glcd_pixel_set().
#define GLCD_PAGES (GLCD_HEIGHT / GLCD_PAGE_PIXELS)
Referenced by glcd_clear(), and glcd_update().
#define GLCD_PIXEL_BITS 1
#define GLCD_PIXEL_BYTES (GLCD_PAGES * GLCD_WIDTH * GLCD_PIXEL_BITS)
#define GLCD_WIDTH 128
Referenced by glcd_clear(), glcd_pixel_set(), and glcd_update_page().
Typedef Documentation
typedef glcd_private_t glcd_obj_t
typedef glcd_obj_t* glcd_t
Function Documentation
void glcd_clear (glcd_t glcd)
References GLCD_PAGES, glcd_update(), GLCD_WIDTH, glcd_private_t::modified, and glcd_private_t::screen.
Referenced by glcd_init().
void glcd_contrast_set (glcd_t glcd, uint8_t contrast)
References GLCD_CMD_REF_VOLTAGE_MODE, GLCD_CMD_REG_RESISTOR, glcd_command_mode(), and glcd_send().
glcd_t glcd_init (glcd_obj_t * obj, const glcd_cfg_t * cfg)
References glcd_private_t::cfg, glcd_clear(), glcd_config(), GLCD_SPI_DIVISOR, glcd_private_t::modified, and glcd_private_t::spi.
void glcd_pixel_set (glcd_t glcd, uint16_t x, uint16_t y, uint8_t val)
References GLCD_HEIGHT, GLCD_PAGE_PIXELS, GLCD_WIDTH, glcd_private_t::modified, and glcd_private_t::screen.
Referenced by display_pixel(), and glcd_draw_line().
void glcd_shutdown (glcd_obj_t * obj)
void glcd_update (glcd_t glcd)
References GLCD_PAGES, glcd_update_page(), and glcd_private_t::modified.
Referenced by glcd_clear(), glcd_text(), and textview_putc().