mbuttons.h File Reference
#include `button.h`
Data Structures
struct mbuttons_private_t
Typedefs
typedef mbuttons_private_t mbuttons_obj_t
typedef mbuttons_obj_t * mbuttons_t
Functions
void mbuttons_init (mbuttons_obj_t *mbuttons, button_obj_t *mbuttons_info, const button_cfg_t *row_config, uint8_t rows_num, const button_cfg_t *col_config, uint8_t cols_num, uint8_t poll_count)
void mbuttons_poll (mbuttons_t mbuttons)
bool mbuttons_any_state_p (mbuttons_t mbuttons, button_state_t state)
static bool mbuttons_any_pushed_p (mbuttons_t mbuttons)
bool mbuttons_any_down_p (mbuttons_t mbuttons)
void mbuttons_wakeup_init (mbuttons_t mbuttons)
static bool mbuttons_pushed_p (mbuttons_t mbuttons, uint8_t id)
static bool mbuttons_released_p (mbuttons_t mbuttons, uint8_t id)
static bool mbuttons_held_p (mbuttons_t mbuttons, uint8_t id, uint8_t hold_time)
static bool mbuttons_hold_released_p (mbuttons_t mbuttons, uint8_t id, uint8_t hold_time)
static bool mbuttons_wakeup_p (mbuttons_t mbuttons)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 29 June 2007
Typedef Documentation
typedef mbuttons_private_t mbuttons_obj_t
typedef mbuttons_obj_t* mbuttons_t
Function Documentation
bool mbuttons_any_down_p (mbuttons_t mbuttons)
static bool mbuttons_any_pushed_p (mbuttons_t mbuttons) [static]
References BUTTON_STATE_PUSHED, and mbuttons_any_state_p().
bool mbuttons_any_state_p (mbuttons_t mbuttons, button_state_t state)
References button_state_get(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, and mbuttons_private_t::rows_num.
Referenced by mbuttons_any_pushed_p().
static bool mbuttons_held_p (mbuttons_t mbuttons, uint8_t id, uint8_t hold_time) [static]
References button_held_p(), and mbuttons_private_t::buttons.
static bool mbuttons_hold_released_p (mbuttons_t mbuttons, uint8_t id, uint8_t hold_time) [static]
References button_hold_released_p(), and mbuttons_private_t::buttons.
void mbuttons_init (mbuttons_obj_t * mbuttons, button_obj_t * mbuttons_info, const button_cfg_t * row_config, uint8_t rows_num, const button_cfg_t * col_config, uint8_t cols_num, uint8_t poll_count)
References button_init(), button_poll_count_set(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.
void mbuttons_poll (mbuttons_t mbuttons)
References button_cfg_t::bitmask, button_poll(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, button_cfg_t::port, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.
static bool mbuttons_pushed_p (mbuttons_t mbuttons, uint8_t id) [static]
References button_pushed_p(), and mbuttons_private_t::buttons.
static bool mbuttons_released_p (mbuttons_t mbuttons, uint8_t id) [static]
References button_released_p(), and mbuttons_private_t::buttons.
void mbuttons_wakeup_init (mbuttons_t mbuttons)
References button_cfg_t::bitmask, button_cfg_t::port, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.
static bool mbuttons_wakeup_p (mbuttons_t mbuttons) [static]
References button_pressed_p(), mbuttons_private_t::buttons, and mbuttons_private_t::cols_num.