mbuttons.c File Reference
#include `mbuttons.h`
#include `port.h`
Functions
void mbuttons_init (mbuttons_obj_t *mbuttons, button_obj_t *mbutton_objs, const button_cfg_t *row_config, uint8_t rows_num, const button_cfg_t *col_config, uint8_t cols_num, uint8_t poll_count)
void mbuttons_poll (mbuttons_t mbuttons)
bool mbuttons_any_state_p (mbuttons_t mbuttons, button_state_t state)
void mbuttons_wakeup_init (mbuttons_t mbuttons)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 29 June 2007
Function Documentation
bool mbuttons_any_state_p (mbuttons_t mbuttons, button_state_t state)
References button_state_get(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, and mbuttons_private_t::rows_num.
Referenced by mbuttons_any_pushed_p().
void mbuttons_init (mbuttons_obj_t * mbuttons, button_obj_t * mbutton_objs, const button_cfg_t * row_config, uint8_t rows_num, const button_cfg_t * col_config, uint8_t cols_num, uint8_t poll_count)
References button_init(), button_poll_count_set(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.
void mbuttons_poll (mbuttons_t mbuttons)
References button_cfg_t::bitmask, button_poll(), mbuttons_private_t::buttons, mbuttons_private_t::cols_num, button_cfg_t::port, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.
void mbuttons_wakeup_init (mbuttons_t mbuttons)
References button_cfg_t::bitmask, button_cfg_t::port, mbuttons_private_t::row_config, and mbuttons_private_t::rows_num.