mcleds.c File Reference
#include `mcleds.h`
Functions
mcleds_t mcleds_init (mcleds_obj_t *mcleds, const led_cfg_t *row_config, uint8_t rows_num, const led_cfg_t *col_config, uint8_t cols_num, colourmap_t *colourmap, uint8_t colourmap_size, mcleds_state_t *state, uint8_t update_rate)
bool mcleds_update (mcleds_t mcleds, uint8_t *screen)
void mcleds_enable (mcleds_t mcleds, uint8_t row)
void mcleds_off (mcleds_t mcleds)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 3 July 2007
Function Documentation
void mcleds_enable (mcleds_t mcleds, uint8_t row)
References mcleds_private_t::cleds, cleds_cols_num_get(), cleds_common_set(), cleds_set(), and mcleds_private_t::state.
mcleds_t mcleds_init (mcleds_obj_t * mcleds, const led_cfg_t * row_config, uint8_t rows_num, const led_cfg_t * col_config, uint8_t cols_num, colourmap_t * colourmap, uint8_t colourmap_size, mcleds_state_t * state, uint8_t update_rate)
References mcleds_private_t::cleds, cleds_common_set(), cleds_init(), mcleds_private_t::colourmap, mcleds_private_t::colourmap_size, mcleds_private_t::primary_ticker, mcleds_private_t::state, and TICKER_INIT.
void mcleds_off (mcleds_t mcleds)
References mcleds_private_t::cleds, cleds_cols_num_get(), and cleds_set().
bool mcleds_update (mcleds_t mcleds, uint8_t * screen)
References mcleds_private_t::cleds, cleds_cols_num_get(), cleds_common_set(), cleds_rows_num_get(), cleds_set(), mcleds_private_t::colourmap, mcleds_state_t::duty, mcleds_private_t::primary_ticker, mcleds_private_t::state, and TICKER_UPDATE.