mcleds.h File Reference
#include `config.h`
#include `cleds.h`
#include `colourmap.h`
#include `ticker.h`
Data Structures
struct mcleds_state_t
struct mcleds_private_t
Typedefs
typedef mcleds_private_t mcleds_obj_t
typedef mcleds_obj_t * mcleds_t
Functions
mcleds_t mcleds_init (mcleds_obj_t *mcleds, const led_cfg_t *row_config, uint8_t rows_num, const led_cfg_t *col_config, uint8_t cols_num, colourmap_t *colourmap, uint8_t colourmap_size, mcleds_state_t *state, uint8_t update_rate)
bool mcleds_update (mcleds_t mcleds, uint8_t *screen)
void mcleds_off (mcleds_t mcleds)
void mcleds_enable (mcleds_t mcleds, uint8_t row)
static uint8_t mcleds_disable (mcleds_t mcleds)
static void mcleds_colourmap_set (mcleds_t mcleds, colourmap_t *colourmap, uint8_t colourmap_size)
Detailed Description
Author: M. P. Hayes, UCECE
Date: 3 July 2007
Typedef Documentation
typedef mcleds_private_t mcleds_obj_t
typedef mcleds_obj_t* mcleds_t
Function Documentation
static void mcleds_colourmap_set (mcleds_t mcleds, colourmap_t * colourmap, uint8_t colourmap_size) [static]
References mcleds_private_t::colourmap, and mcleds_private_t::colourmap_size.
static uint8_t mcleds_disable (mcleds_t mcleds) [static]
References mcleds_private_t::cleds, and cleds_common_set().
void mcleds_enable (mcleds_t mcleds, uint8_t row)
References mcleds_private_t::cleds, cleds_cols_num_get(), cleds_common_set(), cleds_set(), and mcleds_private_t::state.
mcleds_t mcleds_init (mcleds_obj_t * mcleds, const led_cfg_t * row_config, uint8_t rows_num, const led_cfg_t * col_config, uint8_t cols_num, colourmap_t * colourmap, uint8_t colourmap_size, mcleds_state_t * state, uint8_t update_rate)
References mcleds_private_t::cleds, cleds_common_set(), cleds_init(), mcleds_private_t::colourmap, mcleds_private_t::colourmap_size, mcleds_private_t::primary_ticker, mcleds_private_t::state, and TICKER_INIT.
void mcleds_off (mcleds_t mcleds)
References mcleds_private_t::cleds, cleds_cols_num_get(), and cleds_set().
bool mcleds_update (mcleds_t mcleds, uint8_t * screen)
References mcleds_private_t::cleds, cleds_cols_num_get(), cleds_common_set(), cleds_rows_num_get(), cleds_set(), mcleds_private_t::colourmap, mcleds_state_t::duty, mcleds_private_t::primary_ticker, mcleds_private_t::state, and TICKER_UPDATE.