mdraw.h File Reference
Simple line drawing routines for GLCD.
#include `config.h`
Data Structures
struct mdraw_private_t
Typedefs
typedef void(* mdraw_pixel_set_t)(void *data, uint8_t col, uint8_t row, uint8_t val)
typedef void(* mdraw_update_t)(void *data)
typedef mdraw_private_t mdraw_obj_t
typedef mdraw_obj_t * mdraw_t
Functions
mdraw_t mdraw_init (mdraw_obj_t *obj, mdraw_pixel_set_t pixel_set, mdraw_update_t update, void *data)
void mdraw_move (mdraw_t this, uint8_t x, uint8_t y)
void mdraw_line (mdraw_t this, uint8_t x_end, uint8_t y_end, uint8_t val)
void mdraw_update (mdraw_t this)
void mdraw_plot (mdraw_t this, uint8_t *data, uint8_t size, uint8_t val)
Detailed Description
Simple line drawing routines for GLCD.
Author: M. P. Hayes, UCECE
Date: 16 Febraury 2008
Typedef Documentation
typedef mdraw_private_t mdraw_obj_t
typedef void(* mdraw_pixel_set_t)(void *data, uint8_t col, uint8_t row, uint8_t val)
typedef mdraw_obj_t* mdraw_t
typedef void(* mdraw_update_t)(void *data)
Function Documentation
mdraw_t mdraw_init (mdraw_obj_t * obj, mdraw_pixel_set_t pixel_set, mdraw_update_t update, void * data)
void mdraw_line (mdraw_t this, uint8_t x_end, uint8_t y_end, uint8_t val)
Referenced by mdraw_plot().
void mdraw_move (mdraw_t this, uint8_t x, uint8_t y)
Referenced by mdraw_plot().
void mdraw_plot (mdraw_t this, uint8_t * data, uint8_t size, uint8_t val)
References mdraw_line(), and mdraw_move().
void mdraw_update (mdraw_t this)