mdraw.c File Reference
#include `mdraw.h`
#include <stdlib.h>
Functions
mdraw_t mdraw_init (mdraw_obj_t *obj, mdraw_pixel_set_t pixel_set, mdraw_update_t update, void *data)
void mdraw_move (mdraw_t this, uint8_t x, uint8_t y)
void mdraw_line (mdraw_t this, uint8_t x_end, uint8_t y_end, uint8_t val)
void mdraw_update (mdraw_t this)
void mdraw_plot (mdraw_t this, uint8_t *data, uint8_t size, uint8_t val)
Function Documentation
mdraw_t mdraw_init (mdraw_obj_t * obj, mdraw_pixel_set_t pixel_set, mdraw_update_t update, void * data)
void mdraw_line (mdraw_t this, uint8_t x_end, uint8_t y_end, uint8_t val)
Referenced by mdraw_plot().
void mdraw_move (mdraw_t this, uint8_t x, uint8_t y)
Referenced by mdraw_plot().
void mdraw_plot (mdraw_t this, uint8_t * data, uint8_t size, uint8_t val)
References mdraw_line(), and mdraw_move().
void mdraw_update (mdraw_t this)