mmelody.c File Reference
Play simple melodies.
#include `mmelody.h`
Defines
#define MMELODY_TRANSPARENT 1
Enumerations
enum { MMELODY_SCALE_SIZE = 12
 }
Functions
static void mmelody_ticker_set (mmelody_t mmelody)
static void mmelody_note_play (mmelody_t mmelody, mmelody_note_t note)
static void mmelody_note_fraction_set (mmelody_t mmelody, uint8_t note_fraction)
static mmelody_note_t mmelody_char_to_note (uint8_t ch)
static const char * mmelody_scan (mmelody_t mmelody, const char *str)
void mmelody_play (mmelody_t mmelody, const char *str)
void mmelody_speed_set (mmelody_t mmelody, mmelody_speed_t speed)
void mmelody_volume_set (mmelody_t mmelody, mmelody_volume_t volume)
void mmelody_update (mmelody_t mmelody)
mmelody_t mmelody_init (mmelody_obj_t *mmelody, uint16_t poll_rate, mmelody_callback_t play_callback, void *play_callback_data)
Detailed Description
Play simple melodies.
Author: M. P. Hayes, UCECE
Date: 20 April 2007
Define Documentation
#define MMELODY_TRANSPARENT 1
Enumeration Type Documentation
anonymous enum
Enumerator:
MMELODY_SCALE_SIZE
Function Documentation
static mmelody_note_t mmelody_char_to_note (uint8_t ch) [static]
Referenced by mmelody_scan().
mmelody_t mmelody_init (mmelody_obj_t * mmelody, uint16_t poll_rate, mmelody_callback_t play_callback, void * play_callback_data)
References mmelody_play(), MMELODY_SPEED_DEFAULT, mmelody_speed_set(), mmelody_private_t::note_fraction, mmelody_private_t::play_callback, mmelody_private_t::play_callback_data, mmelody_private_t::poll_rate, and mmelody_private_t::volume.
static void mmelody_note_fraction_set (mmelody_t mmelody, uint8_t note_fraction) [static]
References mmelody_ticker_set(), and mmelody_private_t::note_fraction.
Referenced by mmelody_play(), and mmelody_scan().
static void mmelody_note_play (mmelody_t mmelody, mmelody_note_t note) [static]
References mmelody_private_t::play_callback, mmelody_private_t::play_callback_data, and mmelody_private_t::volume.
Referenced by mmelody_scan().
void mmelody_play (mmelody_t mmelody, const char * str)
References mmelody_private_t::cur, mmelody_private_t::loop_count, mmelody_private_t::loop_start, mmelody_note_fraction_set(), MMELODY_OCTAVE_DEFAULT, mmelody_private_t::octave, and mmelody_private_t::start.
Referenced by mmelody_init().
static const char* mmelody_scan (mmelody_t mmelody, const char * str) [static]
References mmelody_private_t::loop_count, mmelody_private_t::loop_start, mmelody_char_to_note(), mmelody_note_fraction_set(), mmelody_note_play(), MMELODY_SCALE_SIZE, mmelody_speed_set(), mmelody_private_t::octave, and mmelody_private_t::start.
Referenced by mmelody_update().
void mmelody_speed_set (mmelody_t mmelody, mmelody_speed_t speed)
References mmelody_ticker_set(), and mmelody_private_t::speed.
Referenced by mmelody_init(), and mmelody_scan().
static void mmelody_ticker_set (mmelody_t mmelody) [static]
References mmelody_private_t::note_fraction, mmelody_private_t::poll_rate, mmelody_private_t::speed, mmelody_private_t::ticker, and TICKER_INIT.
Referenced by mmelody_note_fraction_set(), and mmelody_speed_set().
void mmelody_update (mmelody_t mmelody)
References mmelody_private_t::cur, mmelody_scan(), mmelody_private_t::ticker, and TICKER_UPDATE.
void mmelody_volume_set (mmelody_t mmelody, mmelody_volume_t volume)
References mmelody_private_t::volume.