mmelody.h File Reference
Play simple melodies.
#include `config.h`
#include `font.h`
#include `ticker.h`
Data Structures
struct mmelody_private_t
Typedefs
typedef uint8_t mmelody_speed_t
typedef uint8_t mmelody_scale_t
typedef uint8_t mmelody_note_t
typedef uint8_t mmelody_volume_t
typedef mmelody_private_t mmelody_obj_t
typedef mmelody_obj_t * mmelody_t
typedef void(* mmelody_callback_t)(void *data, uint8_t note, uint8_t volume)
Enumerations
enum { MMELODY_OCTAVE_DEFAULT = 4
 }
enum { MMELODY_SPEED_DEFAULT = 200
 }
Functions
mmelody_t mmelody_init (mmelody_obj_t *dev, uint16_t poll_rate, mmelody_callback_t play_callback, void *play_callback_data)
void mmelody_play (mmelody_t mmelody, const char *str)
void mmelody_update (mmelody_t mmelody)
void mmelody_speed_set (mmelody_t mmelody, mmelody_speed_t speed)
void mmelody_volume_set (mmelody_t mmelody, mmelody_volume_t volume)
Detailed Description
Play simple melodies.
Author: M. P. Hayes, UCECE
Date: 20 April 2007
Typedef Documentation
typedef void(* mmelody_callback_t)(void *data, uint8_t note, uint8_t volume)
typedef uint8_t mmelody_note_t
typedef mmelody_private_t mmelody_obj_t
typedef uint8_t mmelody_scale_t
typedef uint8_t mmelody_speed_t
typedef mmelody_obj_t* mmelody_t
typedef uint8_t mmelody_volume_t
Enumeration Type Documentation
anonymous enum
Enumerator:
MMELODY_OCTAVE_DEFAULT
anonymous enum
Enumerator:
MMELODY_SPEED_DEFAULT
Function Documentation
mmelody_t mmelody_init (mmelody_obj_t * dev, uint16_t poll_rate, mmelody_callback_t play_callback, void * play_callback_data)
References mmelody_play(), MMELODY_SPEED_DEFAULT, mmelody_speed_set(), mmelody_private_t::note_fraction, mmelody_private_t::play_callback, mmelody_private_t::play_callback_data, mmelody_private_t::poll_rate, and mmelody_private_t::volume.
void mmelody_play (mmelody_t mmelody, const char * str)
References mmelody_private_t::cur, mmelody_private_t::loop_count, mmelody_private_t::loop_start, mmelody_note_fraction_set(), MMELODY_OCTAVE_DEFAULT, mmelody_private_t::octave, and mmelody_private_t::start.
Referenced by mmelody_init().
void mmelody_speed_set (mmelody_t mmelody, mmelody_speed_t speed)
References mmelody_ticker_set(), and mmelody_private_t::speed.
Referenced by mmelody_init(), and mmelody_scan().
void mmelody_update (mmelody_t mmelody)
References mmelody_private_t::cur, mmelody_scan(), mmelody_private_t::ticker, and TICKER_UPDATE.
void mmelody_volume_set (mmelody_t mmelody, mmelody_volume_t volume)
References mmelody_private_t::volume.