mu1wire.c File Reference
#include <stdio.h>
#include `config.h`
#include `delay.h`
#include `u1wire.h`
#include `irq.h`
#include `port.h`
Defines
#define U1WIRE_DEBUG 1
#define U1WIRE_RELEASE() port_pin_config_pullup (U1WIRE_PORT, U1WIRE_BIT)
#define U1WIRE_DRIVE()
#define U1WIRE_TEST() port_pin_read (U1WIRE_PORT, U1WIRE_BIT)
Enumerations
enum { U1WIRE_READ_ROM = 0x33,
U1WIRE_SKIP_ROM = 0xcc,
U1WIRE_MATCH_ROM = 0x55,
U1WIRE_RECALL = 0xb8
 }
enum { U1WIRE_DELAY_OFFSET = 6,
U1WIRE_ADDR_BYTES = 6
 }
Functions
int8_t u1wire_reset (void)
void u1wire_bit_write (uint8_t value)
void u1wire_byte_write (uint8_t value)
uint8_t u1wire_bit_read (void)
uint8_t u1wire_byte_read (void)
int8_t u1wire_rom_code_read (u1wire_t dev)
int8_t u1wire_command (u1wire_t dev, uint8_t command)
int8_t u1wire_broadcast (uint8_t command)
int8_t u1wire_read (u1wire_t dev, void *data, uint8_t bytes)
int8_t u1wire_write (u1wire_t dev, void *data, uint8_t bytes)
bool u1wire_ready_p (void)
int8_t u1wire_init (u1wire_obj_t *devices, uint8_t devices_max)
Define Documentation
#define U1WIRE_DEBUG 1
#define U1WIRE_DRIVE()
Value:
do {port_pin_config_output (U1WIRE_PORT, U1WIRE_BIT); \
        port_pin_set_low (U1WIRE_PORT, U1WIRE_BIT);} while (0)
Referenced by u1wire_bit_read(), u1wire_bit_write(), and u1wire_reset().
#define U1WIRE_RELEASE() port_pin_config_pullup (U1WIRE_PORT, U1WIRE_BIT)
Referenced by u1wire_bit_read(), u1wire_bit_write(), u1wire_init(), and u1wire_reset().
#define U1WIRE_TEST() port_pin_read (U1WIRE_PORT, U1WIRE_BIT)
Referenced by u1wire_bit_read(), and u1wire_reset().
Enumeration Type Documentation
anonymous enum
Enumerator:
U1WIRE_READ_ROM
U1WIRE_SKIP_ROM
U1WIRE_MATCH_ROM
U1WIRE_RECALL
anonymous enum
Enumerator:
U1WIRE_DELAY_OFFSET
U1WIRE_ADDR_BYTES
Function Documentation
uint8_t u1wire_bit_read (void)
Read a bit from the one wire bus.
Returns: bit read
Referenced by u1wire_byte_read(), u1wire_ready_p(), and u1wire_search().
void u1wire_bit_write (uint8_t value)
Write a bit on the one wire bus.
Parameters:
value bit to write
Referenced by u1wire_byte_write(), and u1wire_search().
int8_t u1wire_broadcast (uint8_t command)
Broadcast command to all devices on one wire bus.
Parameters:
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
uint8_t u1wire_byte_read (void)
Read a byte from the one wire bus.
Returns: byte read
Referenced by u1wire_read().
void u1wire_byte_write (uint8_t value)
Write a byte on the one wire bus.
Parameters:
value byte to write.
Referenced by ds2450_memory_write(), u1wire_broadcast(), u1wire_command(), u1wire_rom_code_read(), u1wire_search(), and u1wire_write().
int8_t u1wire_command (u1wire_t dev, uint8_t command)
Send command to selected device on one wire bus.
Parameters:
dev pointer to one wire device structure
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
Referenced by ds18b20_temp_conversion_start(), ds18b20_temp_read(), ds2450_adc_conversion_start(), ds2450_memory_read(), and ds2450_memory_write().
int8_t u1wire_init (u1wire_obj_t * devices, uint8_t devices_max)
References U1WIRE_ERR_MULTIPLE_DEVICES, U1WIRE_RELEASE, and u1wire_rom_code_read().
int8_t u1wire_read (u1wire_t dev, void * data, uint8_t bytes)
References u1wire_byte_read().
Referenced by ds18b20_temp_read(), ds2450_adc_conversion_start(), ds2450_memory_read(), ds2450_memory_write(), and u1wire_rom_code_read().
bool u1wire_ready_p (void)
Determine if one wire bus operation has completed.
Returns: 1 if one wire bus operation has completed otherwise 0
Referenced by ds18b20_temp_ready_p(), and ds2450_adc_ready_p().
int8_t u1wire_reset (void)
Reset one wire bus.
Returns: 1 if OK, 0 if no device responding, negative if error
Referenced by u1wire_broadcast(), u1wire_command(), u1wire_rom_code_read(), and u1wire_search().
int8_t u1wire_rom_code_read (u1wire_t dev)
References u1wire_obj_t::rom_code, u1wire_byte_write(), u1wire_read(), U1WIRE_READ_ROM, U1WIRE_RECALL, and u1wire_reset().
Referenced by u1wire_init().
int8_t u1wire_write (u1wire_t dev, void * data, uint8_t bytes)
References u1wire_byte_write().
Referenced by ds2450_adc_conversion_start(), ds2450_memory_read(), ds2450_memory_write(), and u1wire_command().