nrf2401.c File Reference
Interface routines for the Nordic nRF2401 tranceiver chip.
#include `nrf2401.h`
#include `delay.h`
Defines
#define CHAR_BIT 8
#define NRF_DATA_READY_P(DEV) (port_pins_read ((DEV) $\rightarrow$ cfg $\rightarrow$ dr.port, (DEV) $\rightarrow$ cfg $\rightarrow$ dr.bitmask))
#define NRF_CONFIGURATION_REGISTER_SIZE 15
#define NRF_CE_HIGH_SET(DEV) (port_pins_set_high ((DEV) $\rightarrow$ cfg $\rightarrow$ ce.port, (DEV) $\rightarrow$ cfg $\rightarrow$ ce.bitmask))
#define NRF_CE_LOW_SET(DEV) (port_pins_set_low ((DEV) $\rightarrow$ cfg $\rightarrow$ ce.port, (DEV) $\rightarrow$ cfg $\rightarrow$ ce.bitmask))
#define NRF_CS_HIGH_SET(DEV) (port_pins_set_high ((DEV) $\rightarrow$ cfg $\rightarrow$ cs.port, (DEV) $\rightarrow$ cfg $\rightarrow$ cs.bitmask))
#define NRF_CS_LOW_SET(DEV) (port_pins_set_low ((DEV) $\rightarrow$ cfg $\rightarrow$ cs.port, (DEV) $\rightarrow$ cfg $\rightarrow$ cs.bitmask))
Enumerations
enum { NRF_CHANNEL_NUMBER_MAX = 83
 }
enum { NRF_CONFIG_DELAY_US = 20
 }
enum { NRF_LINE_TIME_ENABLE_US = 10
 }
enum { NRF_T_SB_ACTIVE = 202
 }
Functions
void nrf_standby (nrf_t nrf)
void nrf_enable (nrf_t nrf)
nrf_t nrf_init (nrf_obj_t *dev, const nrf_cfg_t *cfg)
static void nrf_configure (nrf_t nrf, uint8_t size)
static void nrf_dir_set (nrf_t nrf, uint8_t mode)
static void nrf_channel_set (nrf_t nrf, uint8_t channel)
static void nrf_power_set (nrf_t nrf, uint8_t rf_power)
static void nrf_xtal_freq_set (nrf_t nrf, uint8_t freq)
static void nrf_data_rate_set (nrf_t nrf, uint8_t data_rate)
static void nrf_comms_mode_set (nrf_t nrf, uint8_t mode)
static void nrf_single_or_dual_channel_set (nrf_t nrf, uint8_t mode)
static void nrf_crc_status_set (nrf_t nrf, uint8_t status)
static void nrf_crc_length_set (nrf_t nrf, uint8_t length)
static void nrf_address_length_set (nrf_t nrf, uint8_t length)
static void nrf_address1_set (nrf_t nrf, nrf_address_t *address)
static void nrf_address2_set (nrf_t nrf, nrf_address_t *address)
static void nrf_payload_length1_set (nrf_t nrf, uint8_t length)
static void nrf_payload_length2_set (nrf_t nrf, uint8_t length)
static uint8_t nrf_payload_length1_get (nrf_t nrf)
uint8_t nrf_receive (nrf_t nrf, nrf_node_t *node, void *buffer, uint8_t len, uint8_t ms_to_wait)
uint8_t nrf_transmit (nrf_t nrf, nrf_node_t *node, void *buffer, uint8_t len)
bool nrf_data_ready_p (nrf_t nrf)
bool nrf_setup (nrf_t nrf, uint8_t payload_size)
Detailed Description
Interface routines for the Nordic nRF2401 tranceiver chip.
Author: Michael Hayes / Tony Culliford
Date: 7 December 2004
Define Documentation
#define CHAR_BIT 8
Referenced by isqrt(), isqrt32(), nrf_payload_length1_get(), nrf_setup(), and nrf_transmit().
#define NRF_CE_HIGH_SET(DEV) (port_pins_set_high ((DEV) $\rightarrow$ cfg $\rightarrow$ ce.port, (DEV) $\rightarrow$ cfg $\rightarrow$ ce.bitmask))
Referenced by nrf_enable(), and nrf_transmit().
#define NRF_CE_LOW_SET(DEV) (port_pins_set_low ((DEV) $\rightarrow$ cfg $\rightarrow$ ce.port, (DEV) $\rightarrow$ cfg $\rightarrow$ ce.bitmask))
Referenced by nrf_configure(), nrf_standby(), and nrf_transmit().
#define NRF_CONFIGURATION_REGISTER_SIZE 15
Referenced by nrf_receive(), and nrf_setup().
#define NRF_CS_HIGH_SET(DEV) (port_pins_set_high ((DEV) $\rightarrow$ cfg $\rightarrow$ cs.port, (DEV) $\rightarrow$ cfg $\rightarrow$ cs.bitmask))
Referenced by nrf_configure().
#define NRF_CS_LOW_SET(DEV) (port_pins_set_low ((DEV) $\rightarrow$ cfg $\rightarrow$ cs.port, (DEV) $\rightarrow$ cfg $\rightarrow$ cs.bitmask))
Referenced by nrf_configure(), nrf_enable(), and nrf_standby().
#define NRF_DATA_READY_P(DEV) (port_pins_read ((DEV) $\rightarrow$ cfg $\rightarrow$ dr.port, (DEV) $\rightarrow$ cfg $\rightarrow$ dr.bitmask))
Referenced by nrf_data_ready_p(), and nrf_receive().
Enumeration Type Documentation
anonymous enum
Enumerator:
NRF_CHANNEL_NUMBER_MAX
anonymous enum
Enumerator:
NRF_CONFIG_DELAY_US
anonymous enum
Enumerator:
NRF_LINE_TIME_ENABLE_US
anonymous enum
Enumerator:
NRF_T_SB_ACTIVE
Function Documentation
static void nrf_address1_set (nrf_t nrf, nrf_address_t * address) [static]
References nrf_config_bits_t::addr_1, nrf_config_t::bits, and nrf_obj_t::config.
Referenced by nrf_receive().
static void nrf_address2_set (nrf_t nrf, nrf_address_t * address) [static]
References nrf_config_bits_t::addr_2, nrf_config_t::bits, and nrf_obj_t::config.
static void nrf_address_length_set (nrf_t nrf, uint8_t length) [static]
References nrf_config_bits_t::addr_w, nrf_config_t::bits, and nrf_obj_t::config.
Referenced by nrf_setup().
static void nrf_channel_set (nrf_t nrf, uint8_t channel) [static]
References nrf_config_t::bits, nrf_obj_t::config, NRF_CHANNEL_NUMBER_MAX, nrf_configure(), and nrf_config_bits_t::rx_ch_num.
Referenced by nrf_receive(), nrf_setup(), and nrf_transmit().
static void nrf_comms_mode_set (nrf_t nrf, uint8_t mode) [static]
References nrf_config_t::bits, nrf_config_bits_t::cm, and nrf_obj_t::config.
Referenced by nrf_setup().
static void nrf_configure (nrf_t nrf, uint8_t size) [static]
References nrf_config_t::bytes, nrf_obj_t::config, NRF_CE_LOW_SET, NRF_CONFIG_DELAY_US, NRF_CS_HIGH_SET, NRF_CS_LOW_SET, NRF_LINE_TIME_ENABLE_US, and nrf_obj_t::spi.
Referenced by nrf_channel_set(), nrf_dir_set(), nrf_receive(), nrf_setup(), and nrf_transmit().
static void nrf_crc_length_set (nrf_t nrf, uint8_t length) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::crc_l.
Referenced by nrf_setup().
static void nrf_crc_status_set (nrf_t nrf, uint8_t status) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::crc_en.
Referenced by nrf_setup().
static void nrf_data_rate_set (nrf_t nrf, uint8_t data_rate) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::rfdr_sb.
Referenced by nrf_setup().
bool nrf_data_ready_p (nrf_t nrf)
References NRF_DATA_READY_P.
static void nrf_dir_set (nrf_t nrf, uint8_t mode) [static]
References nrf_config_t::bits, nrf_obj_t::config, nrf_configure(), and nrf_config_bits_t::rxen.
Referenced by nrf_receive(), nrf_setup(), and nrf_transmit().
void nrf_enable (nrf_t nrf)
References NRF_CE_HIGH_SET, and NRF_CS_LOW_SET.
Referenced by nrf_receive().
nrf_t nrf_init (nrf_obj_t * dev, const nrf_cfg_t * cfg)
References nrf_cfg_t::ce, nrf_obj_t::cfg, nrf_cfg_t::cs, nrf_cfg_t::dr, nrf_cfg_t::spi, and nrf_obj_t::spi.
static uint8_t nrf_payload_length1_get (nrf_t nrf) [static]
References nrf_config_t::bits, CHAR_BIT, nrf_obj_t::config, and nrf_config_bits_t::data1_w.
Referenced by nrf_receive().
static void nrf_payload_length1_set (nrf_t nrf, uint8_t length) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::data1_w.
Referenced by nrf_setup().
static void nrf_payload_length2_set (nrf_t nrf, uint8_t length) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::data2_w.
static void nrf_power_set (nrf_t nrf, uint8_t rf_power) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::rf_pwr.
Referenced by nrf_setup().
uint8_t nrf_receive (nrf_t nrf, nrf_node_t * node, void * buffer, uint8_t len, uint8_t ms_to_wait)
References nrf_link_t::address, nrf_link_t::channel, nrf_address1_set(), nrf_channel_set(), NRF_CONFIGURATION_REGISTER_SIZE, nrf_configure(), NRF_DATA_READY_P, nrf_dir_set(), nrf_enable(), nrf_payload_length1_get(), NRF_RX_MODE, nrf_standby(), nrf_node_t::rx, and nrf_obj_t::spi.
Referenced by nrf_acknowledge_wait(), nrf_announce(), and nrf_read().
bool nrf_setup (nrf_t nrf, uint8_t payload_size)
References CHAR_BIT, nrf_address_length_set(), nrf_channel_set(), nrf_comms_mode_set(), NRF_CONFIGURATION_REGISTER_SIZE, nrf_configure(), NRF_CRC_16, NRF_CRC_ENABLED, nrf_crc_length_set(), nrf_crc_status_set(), NRF_DATA_1M, nrf_data_rate_set(), nrf_dir_set(), nrf_payload_length1_set(), NRF_POWER_0, nrf_power_set(), NRF_RX_MODE, NRF_SHOCKBURST, NRF_SINGLE_CHANNEL, nrf_single_or_dual_channel_set(), NRF_XTAL_FREQ_16M, and nrf_xtal_freq_set().
static void nrf_single_or_dual_channel_set (nrf_t nrf, uint8_t mode) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::rx2_en.
Referenced by nrf_setup().
void nrf_standby (nrf_t nrf)
References NRF_CE_LOW_SET, and NRF_CS_LOW_SET.
Referenced by nrf_receive().
uint8_t nrf_transmit (nrf_t nrf, nrf_node_t * node, void * buffer, uint8_t len)
References nrf_config_bits_t::addr_w, nrf_link_t::address, nrf_config_t::bits, nrf_address_t::bytes, nrf_link_t::channel, CHAR_BIT, nrf_obj_t::config, nrf_config_bits_t::crc_en, nrf_config_bits_t::crc_l, nrf_config_bits_t::data1_w, NRF_CE_HIGH_SET, NRF_CE_LOW_SET, nrf_channel_set(), nrf_configure(), NRF_CRC_8, NRF_CRC_ENABLED, NRF_DATA_1M, nrf_dir_set(), NRF_LINE_TIME_ENABLE_US, NRF_T_SB_ACTIVE, NRF_TX_MODE, nrf_config_bits_t::rfdr_sb, nrf_obj_t::spi, and nrf_node_t::tx.
Referenced by nrf_acknowledge(), nrf_announce(), and nrf_write().
static void nrf_xtal_freq_set (nrf_t nrf, uint8_t freq) [static]
References nrf_config_t::bits, nrf_obj_t::config, and nrf_config_bits_t::xo_f.
Referenced by nrf_setup().