nrf2401.h File Reference
Interface routines for the Nordic nrf2401 tranceiver chip.
#include `config.h`
#include `spi.h`
#include `port.h`
Data Structures
struct nrf_address_t
struct nrf_link_t
struct nrf_node_t
struct nrf_config_bits_t
union nrf_config_t
struct nrf_cfg_t
struct nrf_obj_t
Defines
#define NRF_CFG(CHANNEL, DIVISOR, CS_PORT, CS_BIT, CE_PORT, CE_BIT, DR_PORT, DR_BIT) {{(CHANNEL), (DIVISOR), {0, 0}}, {CS_PORT, BIT (CS_BIT)}, {CE_PORT, BIT (CE_BIT)}, {DR_PORT, BIT (DR_BIT)}}
#define NRF_PAYLOAD_SIZE 25
#define NRF_DEFAULT_ADDRESS {0xFD, 0xCA, 0x7E, 0xA9, 0x52}
Typedefs
typedef uint8_t nrf_device_id_t [NRF_DEVICE_ID_SIZE]
typedef uint8_t nrf_channel_t
typedef nrf_obj_t * nrf_t
Enumerations
enum { NRF_DEVICE_ID_SIZE = 8
 }
enum nrf_id_t { NRF_BROADCAST_SLAVE_ID = 0xFE,
NRF_MASTER_ID = 0xFF
 }
enum { NRF_TX_MODE = 0,
NRF_RX_MODE = 1
 }
enum { NRF_DIRECT = 0,
NRF_SHOCKBURST = 1
 }
enum { NRF_CRC_8 = 0,
NRF_CRC_16 = 1
 }
enum { NRF_CRC_DISABLED = 0,
NRF_CRC_ENABLED = 1
 }
enum { NRF_POWER_20,
NRF_POWER_10,
NRF_POWER_5,
NRF_POWER_0
 }
enum { NRF_SINGLE_CHANNEL = 0,
NRF_DUAL_CHANNEL = 1
 }
enum { NRF_DATA_250K = 0,
NRF_DATA_1M = 1
 }
enum {
NRF_XTAL_FREQ_4M,
NRF_XTAL_FREQ_8M,
NRF_XTAL_FREQ_12M,
NRF_XTAL_FREQ_16M,
NRF_XTAL_FREQ_20M
 }
enum { NRF_TIMEOUT_ACK_MS = 10
 }
enum { NRF_ACK_DELAY_US = 600
 }
Functions
nrf_t nrf_init (nrf_obj_t *dev, const nrf_cfg_t *cfg)
bool nrf_setup (nrf_t nrf, uint8_t payload_size)
uint8_t nrf_transmit (nrf_t nrf, nrf_node_t *node, void *buffer, uint8_t len)
uint8_t nrf_receive (nrf_t nrf, nrf_node_t *node, void *buffer, uint8_t len, uint8_t ms_to_wait)
bool nrf_data_ready_p (nrf_t nrf)
Detailed Description
Interface routines for the Nordic nrf2401 tranceiver chip.
Author: Michael Hayes
Date: 7 December 2004
Define Documentation
#define NRF_CFG(CHANNEL, DIVISOR, CS_PORT, CS_BIT, CE_PORT, CE_BIT, DR_PORT, DR_BIT) {{(CHANNEL), (DIVISOR), {0, 0}}, {CS_PORT, BIT (CS_BIT)}, {CE_PORT, BIT (CE_BIT)}, {DR_PORT, BIT (DR_BIT)}}
#define NRF_DEFAULT_ADDRESS {0xFD, 0xCA, 0x7E, 0xA9, 0x52}
Referenced by nrf_node_create().
#define NRF_PAYLOAD_SIZE 25
Referenced by nrf_acknowledge(), nrf_acknowledge_wait(), nrf_devices_enumerate(), nrf_read_data(), and nrf_write().
Typedef Documentation
typedef uint8_t nrf_channel_t
typedef uint8_t nrf_device_id_t[NRF_DEVICE_ID_SIZE]
typedef nrf_obj_t* nrf_t
Enumeration Type Documentation
anonymous enum
Enumerator:
NRF_DEVICE_ID_SIZE
anonymous enum
Enumerator:
NRF_TX_MODE
NRF_RX_MODE
anonymous enum
Enumerator:
NRF_DIRECT
NRF_SHOCKBURST
anonymous enum
Enumerator:
NRF_CRC_8
NRF_CRC_16
anonymous enum
Enumerator:
NRF_CRC_DISABLED
NRF_CRC_ENABLED
anonymous enum
Enumerator:
NRF_POWER_20
NRF_POWER_10
NRF_POWER_5
NRF_POWER_0
anonymous enum
Enumerator:
NRF_SINGLE_CHANNEL
NRF_DUAL_CHANNEL
anonymous enum
Enumerator:
NRF_DATA_250K
NRF_DATA_1M
anonymous enum
Enumerator:
NRF_XTAL_FREQ_4M
NRF_XTAL_FREQ_8M
NRF_XTAL_FREQ_12M
NRF_XTAL_FREQ_16M
NRF_XTAL_FREQ_20M
anonymous enum
Enumerator:
NRF_TIMEOUT_ACK_MS
anonymous enum
Enumerator:
NRF_ACK_DELAY_US
enum nrf_id_t
Enumerator:
NRF_BROADCAST_SLAVE_ID
NRF_MASTER_ID
Function Documentation
bool nrf_data_ready_p (nrf_t nrf)
References NRF_DATA_READY_P.
nrf_t nrf_init (nrf_obj_t * dev, const nrf_cfg_t * cfg)
References nrf_cfg_t::ce, nrf_obj_t::cfg, nrf_cfg_t::cs, nrf_cfg_t::dr, nrf_cfg_t::spi, and nrf_obj_t::spi.
uint8_t nrf_receive (nrf_t nrf, nrf_node_t * node, void * buffer, uint8_t len, uint8_t ms_to_wait)
References nrf_link_t::address, nrf_link_t::channel, nrf_address1_set(), nrf_channel_set(), NRF_CONFIGURATION_REGISTER_SIZE, nrf_configure(), NRF_DATA_READY_P, nrf_dir_set(), nrf_enable(), nrf_payload_length1_get(), NRF_RX_MODE, nrf_standby(), nrf_node_t::rx, and nrf_obj_t::spi.
Referenced by nrf_acknowledge_wait(), nrf_announce(), and nrf_read().
bool nrf_setup (nrf_t nrf, uint8_t payload_size)
References CHAR_BIT, nrf_address_length_set(), nrf_channel_set(), nrf_comms_mode_set(), NRF_CONFIGURATION_REGISTER_SIZE, nrf_configure(), NRF_CRC_16, NRF_CRC_ENABLED, nrf_crc_length_set(), nrf_crc_status_set(), NRF_DATA_1M, nrf_data_rate_set(), nrf_dir_set(), nrf_payload_length1_set(), NRF_POWER_0, nrf_power_set(), NRF_RX_MODE, NRF_SHOCKBURST, NRF_SINGLE_CHANNEL, nrf_single_or_dual_channel_set(), NRF_XTAL_FREQ_16M, and nrf_xtal_freq_set().
uint8_t nrf_transmit (nrf_t nrf, nrf_node_t * node, void * buffer, uint8_t len)
References nrf_config_bits_t::addr_w, nrf_link_t::address, nrf_config_t::bits, nrf_address_t::bytes, nrf_link_t::channel, CHAR_BIT, nrf_obj_t::config, nrf_config_bits_t::crc_en, nrf_config_bits_t::crc_l, nrf_config_bits_t::data1_w, NRF_CE_HIGH_SET, NRF_CE_LOW_SET, nrf_channel_set(), nrf_configure(), NRF_CRC_8, NRF_CRC_ENABLED, NRF_DATA_1M, nrf_dir_set(), NRF_LINE_TIME_ENABLE_US, NRF_T_SB_ACTIVE, NRF_TX_MODE, nrf_config_bits_t::rfdr_sb, nrf_obj_t::spi, and nrf_node_t::tx.
Referenced by nrf_acknowledge(), nrf_announce(), and nrf_write().