rf.h File Reference
Higher-level routines for interfacing to a wireless link.
#include `nrf_config.h`
Data Structures
struct rf_node_t
struct rf_probe_t
Defines
#define RF_PROBE_NOT_FOUND 0xFD
#define RF_PAYLOAD_SIZE NRF_PAYLOAD_SIZE
#define RF_RETRIES_MAX 30
Typedefs
typedef uint8_t rf_channel_t
typedef uint8_t rf_size_t
Enumerations
enum rf_id_t { RF_BROADCAST_SLAVE_ID = 0xFE,
RF_MASTER_ID = 0xFF
 }
enum { RF_BROADCAST_CHANNEL = 0
 }
enum { RF_READ_WAIT_MS = 2
 }
enum { RF_WRITE_WAIT_MS = 4
 }
enum { RF_READY_WAIT_US = 100
 }
enum { RF_READY_WAIT2_US = 300
 }
enum { RF_DEVICE_ID_SIZE = 8
 }
enum rf_cmd_t {
RF_CMD_ACK = 0x61,
RF_CMD_DATA_START,
RF_CMD_CHANNEL_SET,
RF_CMD_TIMESTAMP_REQ,
RF_CMD_BROADCAST_MODE,
RF_CMD_BROADCAST_EXIT,
RF_CMD_DEVICE_ID_GET,
RF_CMD_DEVICE_ID_RESPONSE,
RF_CMD_ENUMERATE_DEVICE,
RF_CMD_RESEND_PACKET,
RF_CMD_ALL_PACKETS_RECEIVED,
RF_CMD_SIZE
 }
Functions
rf_address_t * rf_address_calc (rf_id_t id)
rf_t rf_init (rf_obj_t *rf, rf_cfg_t *cfg)
uint8_t rf_acknowledge_wait (rf_t rf, rf_node_t *node, rf_cmd_t command, time_t *timestamp)
void rf_acknowledge (rf_t rf, rf_node_t *node, rf_cmd_t command)
uint8_t rf_probes_enumerate (rf_t rf, rf_probe_t *probes, uint8_t probes_max)
rf_id_t rf_enumeration_response (rf_t rf, uint8_t *device_id, uint8_t *version)
void rf_read_enable (rf_t rf)
void rf_write_setup (rf_t rf, rf_node_t *node)
rf_size_t rf_write (rf_t rf, rf_node_t *node, uint8_t *data, rf_size_t size)
uint16_t rf_write_data (rf_t rf, rf_node_t *node, uint8_t *data, uint16_t size)
void rf_read_setup (rf_t rf, rf_node_t *node)
bool rf_read_ready_p (rf_t rf)
uint16_t rf_read_data (rf_t rf, rf_node_t *node, uint8_t *data, uint16_t size)
rf_size_t rf_read (rf_t rf, uint8_t *data, rf_size_t size, uint8_t ms_to_wait)
void rf_node_make (rf_node_t *node, rf_id_t id, rf_channel_t channel)
rf_size_t rf_transmit (rf_t rf, rf_node_t *dst_node, uint8_t *data, rf_size_t size)
rf_size_t rf_command (rf_t rf, rf_node_t *dst_node, rf_cmd_t command, void *data, rf_size_t data_size)
void rf_command_no_ack (rf_t rf, rf_node_t *dst_node, rf_cmd_t command, void *data, rf_size_t data_size)
void rf_standby (rf_t rf)
Detailed Description
Higher-level routines for interfacing to a wireless link.
Author: Tony Culliford / Michael Hayes
Date: 8 December 2004
Define Documentation
#define RF_PAYLOAD_SIZE NRF_PAYLOAD_SIZE
Referenced by rf_enumeration_response(), rf_probes_enumerate(), and rf_read_data().
#define RF_PROBE_NOT_FOUND 0xFD
Referenced by rf_probes_enumerate(), and rf_probes_search().
#define RF_RETRIES_MAX 30
Typedef Documentation
typedef uint8_t rf_channel_t
typedef uint8_t rf_size_t
Enumeration Type Documentation
anonymous enum
Enumerator:
RF_BROADCAST_CHANNEL
anonymous enum
Enumerator:
RF_READ_WAIT_MS
anonymous enum
Enumerator:
RF_WRITE_WAIT_MS
anonymous enum
Enumerator:
RF_READY_WAIT_US
anonymous enum
Enumerator:
RF_READY_WAIT2_US
anonymous enum
Enumerator:
RF_DEVICE_ID_SIZE
enum rf_cmd_t
Enumerator:
RF_CMD_ACK
RF_CMD_DATA_START
RF_CMD_CHANNEL_SET
RF_CMD_TIMESTAMP_REQ
RF_CMD_BROADCAST_MODE
RF_CMD_BROADCAST_EXIT
RF_CMD_DEVICE_ID_GET
RF_CMD_DEVICE_ID_RESPONSE
RF_CMD_ENUMERATE_DEVICE
RF_CMD_RESEND_PACKET
RF_CMD_ALL_PACKETS_RECEIVED
RF_CMD_SIZE
enum rf_id_t
Enumerator:
RF_BROADCAST_SLAVE_ID
RF_MASTER_ID
Function Documentation
void rf_acknowledge (rf_t rf, rf_node_t * node, rf_cmd_t command)
Referenced by rf_enumeration_response().
uint8_t rf_acknowledge_wait (rf_t rf, rf_node_t * node, rf_cmd_t command, time_t * timestamp)
rf_address_t* rf_address_calc (rf_id_t id)
rf_size_t rf_command (rf_t rf, rf_node_t * dst_node, rf_cmd_t command, void * data, rf_size_t data_size)
Referenced by rf_read_data().
void rf_command_no_ack (rf_t rf, rf_node_t * dst_node, rf_cmd_t command, void * data, rf_size_t data_size)
Referenced by rf_enumeration_response(), and rf_probes_enumerate().
rf_id_t rf_enumeration_response (rf_t rf, uint8_t * device_id, uint8_t * version)
References rf_acknowledge(), RF_BROADCAST_CHANNEL, RF_BROADCAST_SLAVE_ID, RF_CMD_DEVICE_ID_RESPONSE, RF_CMD_ENUMERATE_DEVICE, rf_command_no_ack(), RF_DEVICE_ID_SIZE, RF_MASTER_ID, rf_node_make(), RF_PAYLOAD_SIZE, RF_PROBE_ENUMERATE_WAIT_MS, rf_read(), rf_read_enable(), and rf_read_setup().
rf_t rf_init (rf_obj_t * rf, rf_cfg_t * cfg)
void rf_node_make (rf_node_t * node, rf_id_t id, rf_channel_t channel)
Referenced by rf_enumeration_response(), and rf_probes_enumerate().
uint8_t rf_probes_enumerate (rf_t rf, rf_probe_t * probes, uint8_t probes_max)
References rf_node_t::channel, rf_probe_t::device_id, rf_node_t::id, rf_probe_t::node, RF_BROADCAST_CHANNEL, RF_BROADCAST_SLAVE_ID, RF_CMD_DEVICE_ID_GET, RF_CMD_DEVICE_ID_RESPONSE, RF_CMD_ENUMERATE_DEVICE, rf_command_no_ack(), RF_DEVICE_ID_SIZE, RF_ENUMERATE_REPEAT_NUM, RF_MASTER_ID, rf_node_make(), RF_PAYLOAD_SIZE, RF_PROBE_NOT_FOUND, RF_PROBE_RESPONSE_WAIT_MS, rf_probes_search(), rf_read(), rf_read_enable(), rf_read_setup(), RF_UNACK_CMD_REPEAT_DELAY_MS, and RF_UNACK_CMD_REPEAT_NUM.
rf_size_t rf_read (rf_t rf, uint8_t * data, rf_size_t size, uint8_t ms_to_wait)
Referenced by rf_enumeration_response(), rf_probes_enumerate(), and rf_read_data().
uint16_t rf_read_data (rf_t rf, rf_node_t * node, uint8_t * data, uint16_t size)
References RF_CMD_ALL_PACKETS_RECEIVED, RF_CMD_RESEND_PACKET, rf_command(), RF_PAYLOAD_SIZE, rf_read(), rf_read_enable(), and RF_READ_WAIT_MS.
void rf_read_enable (rf_t rf)
Referenced by rf_enumeration_response(), rf_probes_enumerate(), and rf_read_data().
bool rf_read_ready_p (rf_t rf)
void rf_read_setup (rf_t rf, rf_node_t * node)
Referenced by rf_enumeration_response(), and rf_probes_enumerate().
void rf_standby (rf_t rf)
rf_size_t rf_transmit (rf_t rf, rf_node_t * dst_node, uint8_t * data, rf_size_t size)
rf_size_t rf_write (rf_t rf, rf_node_t * node, uint8_t * data, rf_size_t size)
uint16_t rf_write_data (rf_t rf, rf_node_t * node, uint8_t * data, uint16_t size)
void rf_write_setup (rf_t rf, rf_node_t * node)