rf_slave.c File Reference
Slave only wireless routines.
#include <string.h>
#include `rf.h`
#include `delay.h`
Enumerations
enum { RF_PROBE_ENUMERATE_WAIT_MS = 5
 }
Functions
rf_id_t rf_enumeration_response (rf_t rf, uint8_t *device_id, uint8_t *version)
Detailed Description
Slave only wireless routines.
Author: Michael Hayes
Date: 25 March 2005
Enumeration Type Documentation
anonymous enum
Enumerator:
RF_PROBE_ENUMERATE_WAIT_MS
Function Documentation
rf_id_t rf_enumeration_response (rf_t rf, uint8_t * device_id, uint8_t * version)
References rf_acknowledge(), RF_BROADCAST_CHANNEL, RF_BROADCAST_SLAVE_ID, RF_CMD_DEVICE_ID_RESPONSE, RF_CMD_ENUMERATE_DEVICE, rf_command_no_ack(), RF_DEVICE_ID_SIZE, RF_MASTER_ID, rf_node_make(), RF_PAYLOAD_SIZE, RF_PROBE_ENUMERATE_WAIT_MS, rf_read(), rf_read_enable(), and rf_read_setup().