rf_master.c File Reference
Stripped from original rf file wireless.c to handle rf functions only used by the master node.
#include <string.h>
#include `rf.h`
#include `delay.h`
#include `port.h`
#include `target.h`
Defines
#define RF_PROBE_RESPONSE_WAIT_MS 100
#define RF_PROBE_RESPONSE_WAIT_NEXT_MS 5
#define RF_ENUMERATE_REPEAT_NUM 3
#define RF_UNACK_CMD_REPEAT_NUM 3
#define RF_UNACK_CMD_REPEAT_DELAY_MS 2
Functions
static uint8_t rf_probes_search (uint8_t *device_id, rf_probe_t *probes, uint8_t probes_num)
uint8_t rf_probes_enumerate (rf_t rf, rf_probe_t *probes, uint8_t probes_max)
uint16_t rf_read_data (rf_t rf, rf_node_t *node, uint8_t *data, uint16_t size)
Detailed Description
Stripped from original rf file wireless.c to handle rf functions only used by the master node.
Author: MPH
Define Documentation
#define RF_ENUMERATE_REPEAT_NUM 3
Referenced by rf_probes_enumerate().
#define RF_PROBE_RESPONSE_WAIT_MS 100
Referenced by rf_probes_enumerate().
#define RF_PROBE_RESPONSE_WAIT_NEXT_MS 5
#define RF_UNACK_CMD_REPEAT_DELAY_MS 2
Referenced by rf_probes_enumerate().
#define RF_UNACK_CMD_REPEAT_NUM 3
Referenced by rf_probes_enumerate().
Function Documentation
uint8_t rf_probes_enumerate (rf_t rf, rf_probe_t * probes, uint8_t probes_max)
References rf_node_t::channel, rf_probe_t::device_id, rf_node_t::id, rf_probe_t::node, RF_BROADCAST_CHANNEL, RF_BROADCAST_SLAVE_ID, RF_CMD_DEVICE_ID_GET, RF_CMD_DEVICE_ID_RESPONSE, RF_CMD_ENUMERATE_DEVICE, rf_command_no_ack(), RF_DEVICE_ID_SIZE, RF_ENUMERATE_REPEAT_NUM, RF_MASTER_ID, rf_node_make(), RF_PAYLOAD_SIZE, RF_PROBE_NOT_FOUND, RF_PROBE_RESPONSE_WAIT_MS, rf_probes_search(), rf_read(), rf_read_enable(), rf_read_setup(), RF_UNACK_CMD_REPEAT_DELAY_MS, and RF_UNACK_CMD_REPEAT_NUM.
static uint8_t rf_probes_search (uint8_t * device_id, rf_probe_t * probes, uint8_t probes_num) [static]
References RF_DEVICE_ID_SIZE, and RF_PROBE_NOT_FOUND.
Referenced by rf_probes_enumerate().
uint16_t rf_read_data (rf_t rf, rf_node_t * node, uint8_t * data, uint16_t size)
References RF_CMD_ALL_PACKETS_RECEIVED, RF_CMD_RESEND_PACKET, rf_command(), RF_PAYLOAD_SIZE, rf_read(), rf_read_enable(), and RF_READ_WAIT_MS.