ring.c File Reference
Ring buffer implementation.
#include <string.h>
#include `ring.h`
Defines
#define RING_FULL_P(RING, TMP) (RING_WRITE_NUM (RING, TMP) == 0)
#define RING_EMPTY_P(RING) ((RING) $\rightarrow$ in == (RING) $\rightarrow$ out)
Functions
bool ring_empty_p (ring_t *ring)
ring_size_t ring_read_num (ring_t *ring)
ring_size_t ring_write_num (ring_t *ring)
ring_size_t ring_init (ring_t *ring, void *buffer, ring_size_t size)
ring_size_t ring_read (ring_t *ring, void *buffer, ring_size_t size)
ring_size_t ring_write (ring_t *ring, const void *buffer, ring_size_t size)
Detailed Description
Ring buffer implementation.
Author: M. P. Hayes, UCECE
Date: 15 May 2000
Define Documentation
#define RING_EMPTY_P(RING) ((RING) $\rightarrow$ in == (RING) $\rightarrow$ out)
Ring buffer empty predicate.
Referenced by ring_empty_p().
#define RING_FULL_P(RING, TMP) (RING_WRITE_NUM (RING, TMP) == 0)
Define some useful macros for determining number of entries in a ring buffer. Macros are used for run-time speed. Ring buffer full predicate.
Function Documentation
bool ring_empty_p (ring_t * ring)
Return non-zero if the ring buffer is empty.
References RING_EMPTY_P.
Referenced by busart_write_finished_p().
ring_size_t ring_init (ring_t * ring, void * buffer, ring_size_t size)
Initialise a ring buffer structure to use a specified buffer.
Parameters:
ring pointer to ring buffer structure
buffer pointer to memory buffer
size size of memory buffer in bytes
Returns: size size of memory buffer in bytes or zero if error.
References ring_struct::end, ring_struct::in, ring_struct::out, and ring_struct::top.
Referenced by busart_init().
ring_size_t ring_read (ring_t * ring, void * buffer, ring_size_t size)
Read from a ring buffer.
Parameters:
ring pointer to ring buffer structure
buffer pointer to memory buffer
size maximum number of bytes to read
Returns: number of bytes actually read.
References ring_struct::end, ring_struct::out, RING_READ_NUM, and ring_struct::top.
Referenced by busart_read().
ring_size_t ring_read_num (ring_t * ring)
Determine number of bytes in ring buffer ready for reading.
Parameters:
ring pointer to ring buffer structure
Returns: number of bytes in ring buffer ready for reading.
References RING_READ_NUM.
Referenced by busart_read_num().
ring_size_t ring_write (ring_t * ring, const void * buffer, ring_size_t size)
Write to a ring buffer.
Parameters:
ring pointer to ring buffer structure
buffer pointer to memory buffer
size number of bytes to write
Returns: number of bytes actually written.
References ring_struct::end, ring_struct::in, RING_WRITE_NUM, and ring_struct::top.
Referenced by busart_write().
ring_size_t ring_write_num (ring_t * ring)
Determine number of bytes in ring buffer free for writing.
Parameters:
ring pointer to ring buffer structure
Returns: number of bytes in ring buffer free for writing.
References RING_WRITE_NUM.
Referenced by busart_write_num().