scroller.h File Reference
Image scroller.
#include `config.h`
Data Structures
struct scroller_obj_t
Typedefs
typedef scroller_obj_t * scroller_t
Enumerations
enum scroller_dir_t {
SCROLLER_OFF,
SCROLLER_LEFT,
SCROLLER_RIGHT,
SCROLLER_DOWN,
SCROLLER_UP
 }
Functions
scroller_t scroller_init (scroller_t scroller, int rows, int cols, scroller_dir_t dir)
int8_t scroller_update (scroller_t scroller, uint8_t *image, uint8_t *screen)
void scroller_start (scroller_t scroller, uint8_t *image, uint8_t *screen)
uint8_t scroller_speed_scale_get (scroller_t scroller)
static void scroller_stop (scroller_t scroller)
static void scroller_dir_set (scroller_t scroller, scroller_dir_t dir)
static scroller_dir_t scroller_dir_get (scroller_t scroller)
Detailed Description
Image scroller.
Author: M. P. Hayes, UCECE
Date: 7 April 2007
Typedef Documentation
typedef scroller_obj_t* scroller_t
Enumeration Type Documentation
enum scroller_dir_t
Enumerator:
SCROLLER_OFF
SCROLLER_LEFT
SCROLLER_RIGHT
SCROLLER_DOWN
SCROLLER_UP
Function Documentation
static scroller_dir_t scroller_dir_get (scroller_t scroller) [static]
References scroller_obj_t::dir.
Referenced by mtext_scroller_dir_get().
static void scroller_dir_set (scroller_t scroller, scroller_dir_t dir) [static]
References scroller_obj_t::dir.
Referenced by mtext_scroller_dir_set().
scroller_t scroller_init (scroller_t scroller, int rows, int cols, scroller_dir_t dir)
References scroller_obj_t::cols, scroller_obj_t::dir, scroller_obj_t::index, scroller_obj_t::rows, and scroller_obj_t::running.
Referenced by mtext_init().
uint8_t scroller_speed_scale_get (scroller_t scroller)
References scroller_obj_t::cols, scroller_obj_t::dir, scroller_obj_t::rows, SCROLLER_DOWN, SCROLLER_LEFT, SCROLLER_OFF, SCROLLER_RIGHT, and SCROLLER_UP.
Referenced by mtext_speed_set().
void scroller_start (scroller_t scroller, uint8_t * image, uint8_t * screen)
References scroller_obj_t::cols, scroller_obj_t::dir, scroller_obj_t::index, scroller_obj_t::rows, scroller_obj_t::running, and SCROLLER_OFF.
Referenced by mtext_update().
static void scroller_stop (scroller_t scroller) [static]
References scroller_obj_t::running.
int8_t scroller_update (scroller_t scroller, uint8_t * image, uint8_t * screen)
References scroller_obj_t::cols, scroller_obj_t::dir, scroller_obj_t::index, scroller_obj_t::rows, scroller_obj_t::running, SCROLLER_DOWN, SCROLLER_LEFT, SCROLLER_OFF, SCROLLER_RIGHT, and SCROLLER_UP.
Referenced by mtext_update().