squeaker.h File Reference
Play simple tunes with PWM.
#include `config.h`
#include `font.h`
#include `ticker.h`
Data Structures
struct squeaker_private_t
Defines
#define SQUEAKER_DIVISOR(POLL_RATE, FREQ) (POLL_RATE / FREQ + 0.5)
#define SQUEAKER_SCALE_TABLE(POLL_RATE)
Typedefs
typedef uint8_t squeaker_speed_t
typedef uint8_t squeaker_scale_t
typedef uint8_t squeaker_note_t
typedef uint8_t squeaker_duration_t
typedef uint8_t squeaker_period_t
typedef uint8_t squeaker_volume_t
typedef squeaker_private_t squeaker_obj_t
typedef squeaker_obj_t * squeaker_t
Enumerations
enum { SQUEAKER_OCTAVE_DEFAULT = 4
 }
enum { SQUEAKER_SPEED_DEFAULT = 200
 }
enum { SQUEAKER_NOTE_MIN = 40
 }
Functions
squeaker_t squeaker_init (squeaker_obj_t *dev, uint16_t poll_rate, squeaker_scale_t *scale_table)
void squeaker_play (squeaker_t squeaker, const char *str)
int8_t squeaker_update (squeaker_t squeaker)
void squeaker_speed_set (squeaker_t squeaker, squeaker_speed_t speed)
void squeaker_volume_set (squeaker_t squeaker, squeaker_volume_t volume)
Detailed Description
Play simple tunes with PWM.
Author: M. P. Hayes, UCECE
Date: 14 April 2007
Define Documentation
#define SQUEAKER_DIVISOR(POLL_RATE, FREQ) (POLL_RATE / FREQ + 0.5)
#define SQUEAKER_SCALE_TABLE(POLL_RATE)
Value:
{SQUEAKER_DIVISOR (POLL_RATE, 82.41), \
    SQUEAKER_DIVISOR (POLL_RATE, 87.31), \
    SQUEAKER_DIVISOR (POLL_RATE, 92.50), \
    SQUEAKER_DIVISOR (POLL_RATE, 98.00), \
    SQUEAKER_DIVISOR (POLL_RATE, 103.83), \
    SQUEAKER_DIVISOR (POLL_RATE, 110.0), \
    SQUEAKER_DIVISOR (POLL_RATE, 116.54), \
    SQUEAKER_DIVISOR (POLL_RATE, 123.47), \
    SQUEAKER_DIVISOR (POLL_RATE, 130.81), \
    SQUEAKER_DIVISOR (POLL_RATE, 138.59), \
    SQUEAKER_DIVISOR (POLL_RATE, 146.83), \
    SQUEAKER_DIVISOR (POLL_RATE, 155.56)}
Typedef Documentation
typedef uint8_t squeaker_duration_t
typedef uint8_t squeaker_note_t
typedef squeaker_private_t squeaker_obj_t
typedef uint8_t squeaker_period_t
typedef uint8_t squeaker_scale_t
typedef uint8_t squeaker_speed_t
typedef squeaker_obj_t* squeaker_t
typedef uint8_t squeaker_volume_t
Enumeration Type Documentation
anonymous enum
Enumerator:
SQUEAKER_OCTAVE_DEFAULT
anonymous enum
Enumerator:
SQUEAKER_SPEED_DEFAULT
anonymous enum
Enumerator:
SQUEAKER_NOTE_MIN
Function Documentation
squeaker_t squeaker_init (squeaker_obj_t * dev, uint16_t poll_rate, squeaker_scale_t * scale_table)
References squeaker_private_t::holdoff, squeaker_private_t::note_duty, squeaker_private_t::note_period, squeaker_private_t::poll_rate, squeaker_private_t::prescaler, squeaker_private_t::scale_table, SQUEAKER_HOLDOFF_TIME, squeaker_play(), SQUEAKER_PRESCALER, SQUEAKER_SPEED_DEFAULT, squeaker_speed_set(), and squeaker_private_t::volume.
void squeaker_play (squeaker_t squeaker, const char * str)
References squeaker_private_t::cur, squeaker_private_t::loop_count, squeaker_private_t::loop_start, squeaker_private_t::octave, squeaker_note_fraction_set(), SQUEAKER_OCTAVE_DEFAULT, and squeaker_private_t::start.
Referenced by squeaker_init().
void squeaker_speed_set (squeaker_t squeaker, squeaker_speed_t speed)
References squeaker_private_t::speed, and squeaker_ticker_set().
Referenced by squeaker_init(), and squeaker_scan().
int8_t squeaker_update (squeaker_t squeaker)
References squeaker_private_t::cur, squeaker_private_t::note_clock, squeaker_private_t::note_duty, squeaker_private_t::note_holdoff, squeaker_private_t::note_period, squeaker_private_t::prescaler, squeaker_scan(), squeaker_private_t::ticker, and TICKER_UPDATE.
void squeaker_volume_set (squeaker_t squeaker, squeaker_volume_t volume)
References squeaker_private_t::volume.