squeaker.c File Reference
Play simple tunes with PWM.
#include `squeaker.h`
Defines
#define SQUEAKER_TRANSPARENT 1
#define SQUEAKER_HOLDOFF_TIME 50e-3
Enumerations
enum { SQUEAKER_PRESCALER = 256
 }
enum { SQUEAKER_SCALE_SIZE = 12
 }
Functions
static void squeaker_ticker_set (squeaker_t squeaker)
static void squeaker_note_fraction_set (squeaker_t squeaker, uint8_t note_fraction)
void squeaker_note_set (squeaker_t squeaker, squeaker_period_t period, squeaker_period_t duty)
static void squeaker_rest_play (squeaker_t squeaker)
static void squeaker_note_play (squeaker_t squeaker, squeaker_note_t note)
static squeaker_note_t squeaker_char_to_note (uint8_t ch)
static const char * squeaker_scan (squeaker_t squeaker, const char *str)
void squeaker_play (squeaker_t squeaker, const char *str)
void squeaker_speed_set (squeaker_t squeaker, squeaker_speed_t speed)
void squeaker_volume_set (squeaker_t squeaker, squeaker_volume_t volume)
int8_t squeaker_update (squeaker_t squeaker)
squeaker_t squeaker_init (squeaker_obj_t *squeaker, uint16_t poll_rate, squeaker_scale_t *scale_table)
Detailed Description
Play simple tunes with PWM.
Author: M. P. Hayes, UCECE
Date: 14 April 2007
Define Documentation
#define SQUEAKER_HOLDOFF_TIME 50e-3
Referenced by squeaker_init().
#define SQUEAKER_TRANSPARENT 1
Enumeration Type Documentation
anonymous enum
Enumerator:
SQUEAKER_PRESCALER
anonymous enum
Enumerator:
SQUEAKER_SCALE_SIZE
Function Documentation
static squeaker_note_t squeaker_char_to_note (uint8_t ch) [static]
Referenced by squeaker_scan().
squeaker_t squeaker_init (squeaker_obj_t * squeaker, uint16_t poll_rate, squeaker_scale_t * scale_table)
static void squeaker_note_fraction_set (squeaker_t squeaker, uint8_t note_fraction) [static]
References squeaker_private_t::note_fraction, and squeaker_ticker_set().
Referenced by squeaker_play(), and squeaker_scan().
static void squeaker_note_play (squeaker_t squeaker, squeaker_note_t note) [static]
References squeaker_private_t::scale_table, SQUEAKER_NOTE_MIN, squeaker_note_set(), SQUEAKER_SCALE_SIZE, and squeaker_private_t::volume.
Referenced by squeaker_scan().
void squeaker_note_set (squeaker_t squeaker, squeaker_period_t period, squeaker_period_t duty)
References squeaker_private_t::holdoff, squeaker_private_t::note_duty, squeaker_private_t::note_holdoff, and squeaker_private_t::note_period.
Referenced by squeaker_note_play(), and squeaker_rest_play().
void squeaker_play (squeaker_t squeaker, const char * str)
References squeaker_private_t::cur, squeaker_private_t::loop_count, squeaker_private_t::loop_start, squeaker_private_t::octave, squeaker_note_fraction_set(), SQUEAKER_OCTAVE_DEFAULT, and squeaker_private_t::start.
Referenced by squeaker_init().
static void squeaker_rest_play (squeaker_t squeaker) [static]
References squeaker_note_set().
Referenced by squeaker_scan().
static const char* squeaker_scan (squeaker_t squeaker, const char * str) [static]
References squeaker_private_t::loop_count, squeaker_private_t::loop_start, squeaker_private_t::octave, squeaker_char_to_note(), squeaker_note_fraction_set(), squeaker_note_play(), squeaker_rest_play(), SQUEAKER_SCALE_SIZE, squeaker_speed_set(), and squeaker_private_t::start.
Referenced by squeaker_update().
void squeaker_speed_set (squeaker_t squeaker, squeaker_speed_t speed)
References squeaker_private_t::speed, and squeaker_ticker_set().
Referenced by squeaker_init(), and squeaker_scan().
static void squeaker_ticker_set (squeaker_t squeaker) [static]
References squeaker_private_t::note_fraction, squeaker_private_t::poll_rate, squeaker_private_t::speed, SQUEAKER_PRESCALER, squeaker_private_t::ticker, and TICKER_INIT.
Referenced by squeaker_note_fraction_set(), and squeaker_speed_set().
int8_t squeaker_update (squeaker_t squeaker)
References squeaker_private_t::cur, squeaker_private_t::note_clock, squeaker_private_t::note_duty, squeaker_private_t::note_holdoff, squeaker_private_t::note_period, squeaker_private_t::prescaler, squeaker_scan(), squeaker_private_t::ticker, and TICKER_UPDATE.
void squeaker_volume_set (squeaker_t squeaker, squeaker_volume_t volume)
References squeaker_private_t::volume.