stext.h File Reference
Sequenced text.
#include `config.h`
#include `font.h`
#include `seq.h`
Data Structures
struct stext_obj_t
Typedefs
typedef stext_obj_t * stext_t
Enumerations
enum stext_mode_t { STEXT_MODE_NORMAL,
STEXT_MODE_CYCLE,
STEXT_MODE_NUM
 }
Functions
stext_t stext_init (stext_obj_t *dev, font_t *font, void(*callback)(void *data, uint8_t pixel, bool val), void *callback_data)
static void stext_set (stext_t stext, const char *str)
static const char * stext_get (stext_t stext)
static int8_t stext_update (stext_t stext)
Detailed Description
Sequenced text.
Author: M. P. Hayes, UCECE
Date: 2 April 2007
Typedef Documentation
typedef stext_obj_t* stext_t
Enumeration Type Documentation
enum stext_mode_t
Enumerator:
STEXT_MODE_NORMAL
STEXT_MODE_CYCLE
STEXT_MODE_NUM
Function Documentation
static const char* stext_get (stext_t stext) [static]
References stext_obj_t::seq, and seq_get().
stext_t stext_init (stext_obj_t * dev, font_t * font, void(*)(void *data, uint8_t pixel, bool val) callback, void * callback_data)
References stext_obj_t::callback, stext_obj_t::callback_data, stext_obj_t::font, stext_obj_t::seq, stext_obj_t::seq_info, seq_init(), and stext_display().
static void stext_set (stext_t stext, const char * str) [static]
References stext_obj_t::seq, and seq_set().
static int8_t stext_update (stext_t stext) [static]
References stext_obj_t::seq, and seq_update().