usart_dev_struct Struct Reference
Data Fields
int8_t(* putc)(char ch)
int8_t(* getc)(void)
bool(* read_ready_p)(void)
bool(* write_ready_p)(void)
bool(* write_finished_p)(void)
Field Documentation
int8_t(* usart_dev_struct::putc)(char ch)
Referenced by usart_putc().
int8_t(* usart_dev_struct::getc)(void)
Referenced by usart_getc().
bool(* usart_dev_struct::read_ready_p)(void)
Referenced by usart_read_ready_p().
bool(* usart_dev_struct::write_ready_p)(void)
Referenced by usart_write_ready_p().
bool(* usart_dev_struct::write_finished_p)(void)
Referenced by usart_write_finished_p().
The documentation for this struct was generated from the following file:
usart.c