textview.h File Reference
Simple text viewing routines for GLCD.
#include `config.h`
#include `font.h`
Data Structures
struct textview_private_t
Typedefs
typedef void(* textview_pixel_set_t)(void *data, uint8_t col, uint8_t row, uint8_t val)
typedef void(* textview_update_t)(void *data)
typedef textview_private_t textview_obj_t
typedef textview_obj_t * textview_t
Functions
textview_t textview_init (textview_obj_t *obj, char *screen, uint8_t cols, uint8_t rows, font_t *font, textview_pixel_set_t pixel_set, textview_update_t update, void *data)
void textview_goto (textview_t this, uint8_t col, uint8_t row)
void textview_clear (textview_t this)
void textview_redraw (textview_t this)
void textview_font_set (textview_t this, font_t *font)
void textview_putc (textview_t this, char ch)
void textview_puts (textview_t this, const char *string)
void textview_wrap_set (textview_t this, uint8_t enable)
Detailed Description
Simple text viewing routines for GLCD.
Author: M. P. Hayes, UCECE
Date: 16 Febraury 2008
Typedef Documentation
typedef textview_private_t textview_obj_t
typedef void(* textview_pixel_set_t)(void *data, uint8_t col, uint8_t row, uint8_t val)
typedef textview_obj_t* textview_t
typedef void(* textview_update_t)(void *data)
Function Documentation
void textview_clear (textview_t this)
References textview_redraw().
Referenced by textview_init().
void textview_font_set (textview_t this, font_t * font)
References textview_redraw().
void textview_goto (textview_t this, uint8_t col, uint8_t row)
textview_t textview_init (textview_obj_t * obj, char * screen, uint8_t cols, uint8_t rows, font_t * font, textview_pixel_set_t pixel_set, textview_update_t update, void * data)
References textview_clear().
void textview_putc (textview_t this, char ch)
References glcd_update(), and textview_putc_1().
void textview_puts (textview_t this, const char * string)
References textview_putc_1().
void textview_redraw (textview_t this)
References glcd_text().
Referenced by textview_clear(), textview_font_set(), and textview_scroll().
void textview_wrap_set (textview_t this, uint8_t enable)
References TEXTVIEW_FLAG_WRAP.