u1wire.c File Reference
Low level routines to drive Dallas universal 1 wire bus. This only supports a single instance of a 1 wire bus.
#include <stdio.h>
#include `config.h`
#include `delay.h`
#include `u1wire.h`
#include `irq.h`
#include `port.h`
Defines
#define U1WIRE_DEBUG 1
#define U1WIRE_RELEASE() port_pin_config_pullup (U1WIRE_PORT, U1WIRE_BIT)
#define U1WIRE_DRIVE()
#define U1WIRE_TEST() port_pin_read (U1WIRE_PORT, U1WIRE_BIT)
Enumerations
enum { U1WIRE_READ_ROM = 0x33,
U1WIRE_SKIP_ROM = 0xcc,
U1WIRE_MATCH_ROM = 0x55,
U1WIRE_RECALL = 0xb8
 }
enum { U1WIRE_DELAY_OFFSET = 6,
U1WIRE_ADDR_BYTES = 6
 }
Functions
int8_t u1wire_reset (void)
void u1wire_bit_write (uint8_t value)
void u1wire_byte_write (uint8_t value)
uint8_t u1wire_bit_read (void)
uint8_t u1wire_byte_read (void)
static int8_t u1wire_rom_code_read (u1wire_t dev)
int8_t u1wire_command (u1wire_t dev, uint8_t command)
int8_t u1wire_broadcast (uint8_t command)
int8_t u1wire_read (void *data, uint8_t size)
int8_t u1wire_write (void *data, uint8_t size)
bool u1wire_ready_p (void)
int8_t u1wire_init (u1wire_obj_t *device)
Detailed Description
Low level routines to drive Dallas universal 1 wire bus. This only supports a single instance of a 1 wire bus.
Low level routines to drive Dallas universal 1 wire bus.
Author: M. P. Hayes
Date: 16 May 20002
Author: M. P. Hayes
Date: 16 May 20002
Note: This only supports a single instance of a 1 wire bus.
Define Documentation
#define U1WIRE_DEBUG 1
#define U1WIRE_DRIVE()
Value:
do {port_pin_config_output (U1WIRE_PORT, U1WIRE_BIT); \
        port_pin_set_low (U1WIRE_PORT, U1WIRE_BIT);} while (0)
#define U1WIRE_RELEASE() port_pin_config_pullup (U1WIRE_PORT, U1WIRE_BIT)
#define U1WIRE_TEST() port_pin_read (U1WIRE_PORT, U1WIRE_BIT)
Enumeration Type Documentation
anonymous enum
Enumerator:
U1WIRE_READ_ROM
U1WIRE_SKIP_ROM
U1WIRE_MATCH_ROM
U1WIRE_RECALL
anonymous enum
Enumerator:
U1WIRE_DELAY_OFFSET
U1WIRE_ADDR_BYTES
Function Documentation
uint8_t u1wire_bit_read (void)
Read a bit from the one wire bus.
Returns: bit read
References U1WIRE_DELAY_OFFSET, U1WIRE_DRIVE, U1WIRE_RELEASE, and U1WIRE_TEST.
void u1wire_bit_write (uint8_t value)
Write a bit on the one wire bus.
Parameters:
value bit to write
References U1WIRE_DELAY_OFFSET, U1WIRE_DRIVE, and U1WIRE_RELEASE.
int8_t u1wire_broadcast (uint8_t command)
Broadcast command to all devices on one wire bus.
Parameters:
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
References u1wire_byte_write(), u1wire_reset(), and U1WIRE_SKIP_ROM.
uint8_t u1wire_byte_read (void)
Read a byte from the one wire bus.
Returns: byte read
References u1wire_bit_read().
void u1wire_byte_write (uint8_t value)
Write a byte on the one wire bus.
Parameters:
value byte to write.
References u1wire_bit_write().
int8_t u1wire_command (u1wire_t dev, uint8_t command)
Send command to selected device on one wire bus.
Parameters:
dev pointer to one wire device structure
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
References u1wire_obj_t::rom_code, u1wire_byte_write(), U1WIRE_MATCH_ROM, u1wire_reset(), and u1wire_write().
int8_t u1wire_init (u1wire_obj_t * device)
Initialise one wire bus and discover if there is a single device on the bus.
Parameters:
device pointer to one wire device structure
Returns: 1 if OK, 0 if no device responding, negative if error
References U1WIRE_RELEASE, and u1wire_rom_code_read().
int8_t u1wire_read (void * data, uint8_t size)
Read number of bytes of data from one wire bus.
Parameters:
data pointer to buffer to write to
size number of bytes to write
Returns: number of bytes read, 0 if no device responding, negative if error
References u1wire_byte_read().
bool u1wire_ready_p (void)
Determine if one wire bus operation has completed.
Returns: 1 if one wire bus operation has completed otherwise 0
References u1wire_bit_read().
int8_t u1wire_reset (void)
Reset one wire bus.
Returns: 1 if OK, 0 if no device responding, negative if error
References U1WIRE_DRIVE, U1WIRE_ERR_BUS_HIGH, U1WIRE_ERR_BUS_LOW, U1WIRE_ERR_BUS_STUCK, U1WIRE_ERR_PRESENCE_LONG, U1WIRE_ERR_PRESENCE_SHORT, U1WIRE_RELEASE, and U1WIRE_TEST.
static int8_t u1wire_rom_code_read (u1wire_t dev) [static]
Determine the ROM code for a single device on a one wire bus.
Parameters:
dev pointer to one wire device structure
Returns: 1 if OK, 0 if no device responding, negative if error
References u1wire_obj_t::rom_code, u1wire_byte_write(), u1wire_read(), U1WIRE_READ_ROM, U1WIRE_RECALL, and u1wire_reset().
int8_t u1wire_write (void * data, uint8_t size)
Write number of bytes of data from one wire bus.
Parameters:
data pointer to buffer to write to
size number of bytes to write
Returns: number of bytes written, 0 if no device responding, negative if error
References u1wire_byte_write().