u1wire.h File Reference
One wire bus driver.
#include `config.h`
Data Structures
union u1wire_rom_code_t
struct u1wire_obj_t
Typedefs
typedef enum u1wire_err u1wire_err_t
typedef u1wire_obj_t * u1wire_t
Enumerations
enum u1wire_err {
U1WIRE_ERR_BUS_LOW = 1,
U1WIRE_ERR_BUS_STUCK = 2,
U1WIRE_ERR_PRESENCE_SHORT = 3,
U1WIRE_ERR_PRESENCE_LONG = 4,
U1WIRE_ERR_MULTIPLE_DEVICES = 5,
U1WIRE_ERR_BUS_HIGH = 6,
U1WIRE_ERR_CRC = 7,
U1WIRE_ERR_WRONG_DEVICE = 8,
U1WIRE_ERR_DISCONNECT = 9
 }
Functions
bool u1wire_ready_p (void)
int8_t u1wire_reset (void)
void u1wire_bit_write (uint8_t value)
void u1wire_byte_write (uint8_t value)
uint8_t u1wire_bit_read (void)
uint8_t u1wire_byte_read (void)
int8_t u1wire_command (u1wire_t dev, uint8_t command)
int8_t u1wire_broadcast (uint8_t command)
int8_t u1wire_read (void *data, uint8_t size)
int8_t u1wire_write (void *data, uint8_t size)
int8_t u1wire_init (u1wire_obj_t *device)
void u1wire_debug (u1wire_t dev)
Detailed Description
One wire bus driver.
Author: M. P. Hayes, UCECE
Date: 08 June 2002
Note: This interface only supports the one bus but with multiple devices on the bus. This was a deliberate choice that I may regret one day. It keeps the interface simpler, reduces the code size, and most systems will only ever have a single one wire bus. To support multiple one wire buses then run-time configuration will need to be passed as an additional argument to u1wire_init.
Typedef Documentation
typedef enum u1wire_err u1wire_err_t
typedef u1wire_obj_t* u1wire_t
Enumeration Type Documentation
enum u1wire_err
One wire bus error codes.
Enumerator:
U1WIRE_ERR_BUS_LOW
U1WIRE_ERR_BUS_STUCK
U1WIRE_ERR_PRESENCE_SHORT
U1WIRE_ERR_PRESENCE_LONG
U1WIRE_ERR_MULTIPLE_DEVICES
U1WIRE_ERR_BUS_HIGH
U1WIRE_ERR_CRC
U1WIRE_ERR_WRONG_DEVICE
U1WIRE_ERR_DISCONNECT
Function Documentation
uint8_t u1wire_bit_read (void)
Read a bit from the one wire bus.
Returns: bit read
References U1WIRE_DELAY_OFFSET, U1WIRE_DRIVE, U1WIRE_RELEASE, and U1WIRE_TEST.
Referenced by u1wire_byte_read(), u1wire_ready_p(), and u1wire_search().
void u1wire_bit_write (uint8_t value)
Write a bit on the one wire bus.
Parameters:
value bit to write
References U1WIRE_DELAY_OFFSET, U1WIRE_DRIVE, and U1WIRE_RELEASE.
Referenced by u1wire_byte_write(), and u1wire_search().
int8_t u1wire_broadcast (uint8_t command)
Broadcast command to all devices on one wire bus.
Parameters:
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
References u1wire_byte_write(), u1wire_reset(), and U1WIRE_SKIP_ROM.
uint8_t u1wire_byte_read (void)
Read a byte from the one wire bus.
Returns: byte read
References u1wire_bit_read().
Referenced by u1wire_read().
void u1wire_byte_write (uint8_t value)
Write a byte on the one wire bus.
Parameters:
value byte to write.
References u1wire_bit_write().
Referenced by ds2450_memory_write(), u1wire_broadcast(), u1wire_command(), u1wire_rom_code_read(), u1wire_search(), and u1wire_write().
int8_t u1wire_command (u1wire_t dev, uint8_t command)
Send command to selected device on one wire bus.
Parameters:
dev pointer to one wire device structure
command command to send
Returns: 1 if OK, 0 if no device responding, negative if error
References u1wire_obj_t::rom_code, u1wire_byte_write(), U1WIRE_MATCH_ROM, u1wire_reset(), and u1wire_write().
Referenced by ds18b20_temp_conversion_start(), ds18b20_temp_read(), ds2450_adc_conversion_start(), ds2450_memory_read(), and ds2450_memory_write().
void u1wire_debug (u1wire_t dev)
References u1wire_rom_code_t::crc, u1wire_rom_code_t::family, u1wire_rom_code_t::fields, u1wire_obj_t::rom_code, and u1wire_rom_code_t::serial.
int8_t u1wire_init (u1wire_obj_t * device)
Initialise one wire bus and discover if there is a single device on the bus.
Parameters:
device pointer to one wire device structure
Returns: 1 if OK, 0 if no device responding, negative if error
References U1WIRE_RELEASE, and u1wire_rom_code_read().
int8_t u1wire_read (void * data, uint8_t size)
Read number of bytes of data from one wire bus.
Parameters:
data pointer to buffer to write to
size number of bytes to write
Returns: number of bytes read, 0 if no device responding, negative if error
References u1wire_byte_read().
bool u1wire_ready_p (void)
Determine if one wire bus operation has completed.
Returns: 1 if one wire bus operation has completed otherwise 0
References u1wire_bit_read().
Referenced by ds18b20_temp_ready_p(), and ds2450_adc_ready_p().
int8_t u1wire_reset (void)
Reset one wire bus.
Returns: 1 if OK, 0 if no device responding, negative if error
References U1WIRE_DRIVE, U1WIRE_ERR_BUS_HIGH, U1WIRE_ERR_BUS_LOW, U1WIRE_ERR_BUS_STUCK, U1WIRE_ERR_PRESENCE_LONG, U1WIRE_ERR_PRESENCE_SHORT, U1WIRE_RELEASE, and U1WIRE_TEST.
Referenced by u1wire_broadcast(), u1wire_command(), u1wire_rom_code_read(), and u1wire_search().
int8_t u1wire_write (void * data, uint8_t size)
Write number of bytes of data from one wire bus.
Parameters:
data pointer to buffer to write to
size number of bytes to write
Returns: number of bytes written, 0 if no device responding, negative if error
References u1wire_byte_write().